:PROPERTIES:
:ID:       51f7c5ef-86da-44f3-8d30-b58e676628f3
:END:
#+title: ENG231 - Electrical Machines And Transformers - Assignment 2
#+date: [2024-10-05 Sat 11:01]
#+AUTHOR: Baley Eccles - 652137
#+FILETAGS: :Assignment:TODO:UTAS:2024:
#+STARTUP: latexpreview
#+LATEX_HEADER: \usepackage[a4paper, margin=2.5cm]{geometry}
#+LATEX_HEADER_EXTRA: \usepackage{minted}
#+LATEX_HEADER_EXTRA: \usepackage{fontspec}
#+LATEX_HEADER_EXTRA: \setmonofont{Iosevka}
#+LATEX_HEADER_EXTRA: \setminted{fontsize=\small, frame=single, breaklines=true}
#+LATEX_HEADER_EXTRA: \usemintedstyle{emacs}
#+LATEX_HEADER: \usepackage[style=apa, backend=biber]{biblatex}
#+LATEX_HEADER: \addbibresource{ENG231-Ass2-Ref.bib}
#+LATEX_HEADER: \DeclareLanguageMapping{english}{english-apa}
#+LATEX_HEADER_EXTRA: \usepackage{float}


* ENG231 - Electrical Machines And Transformers - Assignment 2
** Part 1: Calculation of transformer winding voltages
  :PROPERTIES:
  :ID: ENG231 - Electrical Machines And Transformers - Assignment 2 - Part 1: Calculation of transformer winding voltages
  :END:
#+BEGIN_SRC octave :exports both :results output :session Part1
h = 90 *10^(-2);
l = 130 *10^(-2);
d = 22 *10^(-2);
g = 1.8 *10^(-3);
mu0 = 4*pi*10^(-7);
mur = 1800;
A = d^2;
Np = 1360;
Ns = 315;
a=Ns/Np;
f = 50;
I = 3.3;

Aeff = A + g*4*d; % Account for fringing
Rgap = g/(mu0*Aeff);
RTopGap = (d/2)/(mu0*mur*A);
RTop = (l-d)/(mu0*mur*A);
Rheight = (h-d-g-d/2)/(mu0*mur*A);
RBottom = (l-d)/(mu0*mur*A);
R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;

Phi=(1/R)*Np*I;
V1 = 2*pi*Np*Phi*f/sqrt(2);
V2 = a*V1;

fprintf('Primary Voltage (V1): %.2f V (RMS)\n', V1);
fprintf('Secondary Voltage (V2): %.2f V (RMS)\n', V2);
#+END_SRC

#+RESULTS:
: Primary Voltage (V1): 15160.91 V (RMS)
: Secondary Voltage (V2): 3511.53 V (RMS)

** Part 2: Specification of transformer design to suit application

We know the voltages and the connection type, this means that we can calculate the turns ratio:
\[a = \frac{V_{secondary}}{\sqrt{3}V_{primary}}\]
#+BEGIN_SRC octave :exports code :results output :session Part2
clc
clear
close all

VpLineToLineRMS = 22*10^3;
VsLineToLineRMS = 400;
a = VsLineToLineRMS/(sqrt(3)*VpLineToLineRMS)
#+END_SRC

#+RESULTS:
: a = 0.010497

Now that we know the turns ratio, we can find specify the layers for both sides and the turns for one side and calculate the other side required turns:
\[a = \frac{N_{secondary}}{N_{primary}}\]
#+BEGIN_SRC octave :exports code :results output :session Part2
Np = 1000
Ns = Np*a
NpLayers = 3;
NsLayers = 2;
#+END_SRC

#+RESULTS:
: Np = 1000
: Ns = 10.497

We also know the max complex power for the three total transformers, by dividing by three we can find the per transformer rating. And with the following equation we can calculate the required current, noting that we have to divide by $\sqrt{3}$ for the primary side, as its $\Delta$ connected.
\[I = \frac{S}{V}\]
#+BEGIN_SRC octave :exports code :results output :session Part2
S = (460*10^3)/3;
IpLineRMS = S/(sqrt(3)*VpLineToLineRMS)
IsRMS = IpLineRMS/(a)
#+END_SRC

#+RESULTS:
: IpLineRMS = 4.0240
: IsRMS = 383.33


Now that we know the current we can find the smallest diameter wiring for our transformer.
#+BEGIN_SRC octave :exports code :results output :session Part2
wireDiameters = [2.03, 2.34, 2.64, 2.95, 3.25, 3.66, 4.06, 4.47, 4.88, 5.39, 5.89, 6.40, 7.01, 7.62, 8.23, 8.84, 9.5, 10.2, 11.0, 11.8, 12.7, 15.0, 17.0, 20.0, 22.0, 24.0, 28.0, 31.0, 34.0, 37.0, 39.0, 41.0] * 10^-3;
maxCurrentRMS = [8.3, 10.5, 13.5, 16.6, 21.2, 26.5, 33.3, 44.2, 52.3, 63.8, 76.4, 90.1, 108, 128, 149, 172, 196, 227, 265, 306, 355, 495, 636, 880, 1064, 1267, 1724, 2113, 2542, 3011, 3345, 3697];

IpMax = 0.05*IpLineRMS;
IsMax = 0.05*IsRMS;

indexPrimary = find(maxCurrentRMS >= IpMax, 1);
wireDiameterP = wireDiameters(indexPrimary)
indexSecondary = find(maxCurrentRMS >= IsMax, 1);
wireDiameterS = wireDiameters(indexSecondary)
#+END_SRC

#+RESULTS:
: wireDiameterP = 2.0300e-03
: wireDiameterS = 3.2500e-03


From here we can specify a magnetic flux density to be used, which can allow us to find the cross sectional and magnetic flux, using the two following equations.
\[\mathcal{E} = \frac{2\pi}{\sqrt{2}}Nf\Phi\]
\[\Phi = B\cdot A\]
#+BEGIN_SRC octave :exports code :results output :session Part2
B = 1.6;
f = 50;
A = ((VpLineToLineRMS)/(4.44*Np*f))/B
A = ((VsLineToLineRMS/sqrt(3))/(4.44*Ns*f))/B
d = sqrt(A)
Phi = B*A;
#+END_SRC

#+RESULTS:
: A = 0.061937
: A = 0.061937
: d = 0.2489

Next we can find the required reluctance using:
\[\Phi = \frac{Ni}{\mathfrak{R}}\]
#+BEGIN_SRC octave :exports code :results output :session Part2
R = (1/Phi)*Np*IpLineRMS
R = (1/Phi)*Ns*IsRMS
#+END_SRC

#+RESULTS:
: R = 4.0605e+04
: R = 4.0605e+04

Knowing the windings diameter and the number of layers, we can find the height.
#+BEGIN_SRC octave :exports code :results output :session Part2
MinHeightPrimary   = (Np/NpLayers)*wireDiameterP
MinHeightSecondary = (Ns/NsLayers)*wireDiameterS

h = max([MinHeightPrimary, MinHeightSecondary])
#+END_SRC

#+RESULTS:
: MinHeightPrimary = 0.6767
: MinHeightSecondary = 0.017058
: h = 0.6767


Now knowing the reluctance we can choose a height and gap size and rearrange the equation from [[id:ENG231 - Electrical Machines And Transformers - Assignment 2 - Part 1: Calculation of transformer winding voltages][Part 1]] for length. This will result in a transformer that meets the voltage and power requirements.
#+BEGIN_SRC octave :exports code :results output :session Part2
mu0 = 4*pi*10^(-7);
mur = 2150;
mu = mu0*mur;
g = 10^-3;
l = d.*mu.*(2.*g ./ (d.*mu0) + 1 ./ mu + 2.*h ./ (d.*mu) - R.*d - 3 ./ mu - 2.*g ./ (d.*mu) - 2 ./ mu) ./ -2
#+END_SRC

#+RESULTS:
: l = 1.0695

How ever, this does not take into account the required gap between the windings in the middle. So, we can add a check that throws an error if the gap is not big enough.
#+BEGIN_SRC octave :exports code :results output :session Part2
gapSize = l-d-d-NpLayers*wireDiameterP-NsLayers*wireDiameterS;
gapSizeMin = max([2*NpLayers*wireDiameterP, 2*NsLayers*wireDiameterS]);
if (gapSize < gapSizeMin)
  sprintf("The gap is not big enough!!!");
endif
if (any([h, l, d, g, Np, Ns, IpLineRMS] <= 0))
  sprintf("One or more values are less than zero, which is in valid!!!");
endif
#+END_SRC

#+RESULTS:

Knowing the dimensions of the transformer we can calculate its volume and hence its mass. Using the iron density as 7874 $kg/m^3$ (\cite{Wiki_Iron}).
#+BEGIN_SRC octave :exports code :results output :session Part2 :TODO: Cite https://en.wikipedia.org/wiki/Iron for the density (Converted to kg/m3)
CoreVolume = 2*l*A+2*(h-g-d-d)*A;
IronDensity = 7874;
weight = CoreVolume*IronDensity;
sprintf("The transformer core weighs %.2f kg \n", weight)
#+END_SRC

#+RESULTS:
: ans = The transformers core weighs 1216.73 kg


Likewise, knowing the dimensions and the windings properties allows us to calculate their volume, length and mass. Using the copper density as 8935 $kg/m^3$ (\cite{Wiki_Copper}).
#+BEGIN_SRC octave :exports code :results output :session Part2
WindingPrimaryLength = 0;
for i = 1:NpLayers
  WindingPrimaryLength += Np*2*(d+(2*i-1)*wireDiameterP/2)/NpLayers;
end

WindingSecondaryLength = 0;
for i = 1:NsLayers
  WindingSecondaryLength += Ns*2*(d+(2*i-1)*wireDiameterS/2)/NsLayers;
end

WindingsPrimaryVolume = pi*(wireDiameterP/2)^2*WindingPrimaryLength;
WindingsSecondaryVolume = pi*(wireDiameterS/2)^2*WindingSecondaryLength;

CopperDensity = 8935;

WindingsPrimaryWeight = WindingsPrimaryVolume*CopperDensity;
WindingsSecondaryWeight = WindingsSecondaryVolume*CopperDensity;

sprintf("The length of the primary windings is %.2f m \n", WindingPrimaryLength)
sprintf("The length of the secondary windings is %.2f m \n", WindingSecondaryLength)

sprintf("The weight of the primary windings is %.2f kg \n", WindingsPrimaryWeight)
sprintf("The weight of the secondary windings is %.2f kg \n", WindingsSecondaryWeight)
#+END_SRC

#+RESULTS:
: ans = The length of the primary windings is 503.83 m
: ans = The length of the secondary windings is 5.29 m
: ans = The weight of the primary windings is 14.57 kg
: ans = The weight of the secondary windings is 0.39 kg



#+RESULTS:
: PowerLossTotal = 1.6664e-04
: ans = The total power loss percentage due to winding resistacne is 0.000167%.


Summing the results allows us to calculate the total weight. Using the copper density as 8935 $kg/m^3$ (\cite{Wiki_Copper}).
#+BEGIN_SRC octave :exports code :results output :session Part2
TotalWeight = weight + WindingsPrimaryWeight + WindingsSecondaryWeight;
sprintf("The total wieght of the transformer is %.2f \n", TotalWeight)
#+END_SRC

#+RESULTS:
: ans = The total wieght of the transformer is 1231.69

Calculating losses due to winding resistance.
#+BEGIN_SRC octave :exports code :results output :session Part2
rho = 16.78*10^-9;
RdcPrimary = rho*WindingPrimaryLength/A;
RdcSecondary = rho*WindingSecondaryLength/A;
RacPrimary = RdcPrimary*1.2;
RacSecondary = RdcSecondary*1.2;
PowerPrimaryLoss = IpLineRMS^2*RacPrimary;
PowerSecondaryLoss = IsRMS^2*RacSecondary;
PowerLossPrimary = (PowerPrimaryLoss/S)*100;
PowerLossSecondary = (PowerSecondaryLoss/S)*100;
PowerLossTotal = PowerLossPrimary+PowerLossSecondary;
sprintf("The total power loss percentage due to winding resistacne is %f%%. \n", PowerLossTotal)
#+END_SRC

Various outputs from the sets of code above was checked with the code from [[id:ENG231 - Electrical Machines And Transformers - Assignment 2 - Part 1: Calculation of transformer winding voltages][Part 1]] and the output satisfied all of the required specifications.

#+BEGIN_SRC octave :exports none :results output :session Verification
h =  0.6767;
l = 1.0695;
d = 0.2489;
g = 1*10^(-3);
mu0 = 4*pi*10^(-7);
mur = 2150;
A = d^2;
Np = 1000;
Ns = 10.497;
a=Ns/Np;
f = 50;
Ip = 4.0240;

Rgap = g/(mu0*A);
RTopGap = (d/2)/(mu0*mur*A);
RTop = (l-d)/(mu0*mur*A);
Rheight = (h-d-g-d/2)/(mu0*mur*A);
RBottom = (l-d)/(mu0*mur*A);
R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;

Phi=(1/R)*Np*Ip;
Vp = 2*pi*Np*Phi*f/sqrt(2);
Vs = a*Vp*sqrt(3);

fprintf('Primary Voltage (Vp): %.2f V (RMS)\n', Vp);
fprintf('Secondary Voltage (Vs): %.2f V (RMS)\n', Vs);
#+END_SRC

#+RESULTS:
: Primary Voltage (Vp): 22019.85 V (RMS)
: Secondary Voltage (Vs): 400.35 V (RMS)


** Part 3: Discussion about transformer design trade-offs
 - Describe the influence that your winding design choices (number of turns and layers) have on transformer size and mass? How might you design for minimum total mass, and what trade-off do you see between iron core mass and copper mass?\\
   The winding choices effect the transformers size and mass by creating restrictions on the size. The number of windings effect how tall the transformer must be and the number of layers effect how long it must be. When we increase the number of windings without increasing the layers we increase the height by forcing more windings to be next to one another. When the number of layers are increased we increase the length by forcing the gap between the primary and secondary windings to be larger. From the output of the code we can see that the mass of the core outweighs the mass of the windings, so, to reduce the total mass we should aim to reduce the core mass. However, when we reduce the mass of the core we will increase the mass of the copper, this is because reducing the number of windings will increase the current per winding and will require a larger winding diameter.

 - Discuss how maximum operating core flux density impacts the required magnetising current and transformer mass?\\
   One of the equations that were used was:
   \[A = \frac{\sqrt{2}V}{2\pi NfB}\]
   from this we can see that reducing the flux density will increase the cross sectional area and hence the mass of the core.

 - Calculate, by adding to your code, the winding losses for your transformer (calculated power loss at rated operation, as a % of rated throughput power)? You may assume that the AC resistance in normal operation is 20% larger than the calculated DC resistance (owing to skin effect and elevated temperatures). Discuss how transformer design influences this loss?\\
   To do this we must calculate the DC resistance of each side, using *Pouillet's law*:
   \[R_{DC} = \rho \frac{l}{A}\]
   Here $\rho$ is the electrical resistivity of copper which is $16.78\ n\Omega\cdot m$ (\cite{Wiki_Copper}). \\
   Now we can find the AC resistance:
   \[R_{AC}=R_{DC}\cdot 1.2\]
   Next we can find the power loss, using:
   \[P_{\textrm{loss}} = I^2R_{AC}\]
   Finally, we can calculate the loss percentage:
   \[\textrm{Power Loss\%} = \frac{P_{\textrm{loss}}}{P_{\textrm{rated}}}\cdot 100\]

 - What aspects of the transformer design (size and mass) or operation (magnetising current, losses) are influenced by core gap width for this transformer?\\
   Increasing the gap will increase the reluctance of the magnetic circuit, which based upon the way I have programmed it, will increase the length of the transformer, and hence its size and mass.

 - For a power transformer, the main components which influence how it impacts the power system are generally the winding resistance and the leakage reactance. Comment on how you think your design choices, in particular the way you have configured each winding, will influence these parameters?\\
   To create a well preforming transformer our goal is to reduce winding resistance and the leakage reactance, To do this we must minimise the length of the windings, as $R_{\textrm{winding}}\propto l$, from Pouillet's law. Like wise, we could also increase the cross sectional area, as $R_{\textrm{winding}}\propto 1/A$.
   To minimise leakage reactance we must minimise the flux leakage, from the following flux leakage equation we can analyse the factors that effect this.
   \[L = \frac{N\phi}{i}\]
   So, the leakage reactance is proportional to the number of turns, magnetic flux and is inversely proportional to the current. Hence, to reduce the leakage reactance we can reduce the number of turns, reduce the magnetic flux or increase the current.


\newpage
\printbibliography
