:PROPERTIES:
:ID:       fb866e0b-9934-4d65-8690-fb73e8c3e1d0
:END:
#+title: KME272 - Assesment 4.1
#+date: [Friday 11th October, 23:59]
#+AUTHOR: Baley Eccles - 652137
#+FILETAGS: :Assignment:TODO:
#+STARTUP: latexpreview


* KME272, Probability & Statistics Assignment 1

** Your tasks

 - First, make sure you have recent versions of R and RStudio installed on your computer.
 - Read and understand the “Introduction to R and Quarto” document.

Below, unless specified otherwise, you can ignore the month and day columns in the data.
** Inspecting the data


 - Load the airquality data into R.

#+begin_src R :session Q1 :export code :results output
outputrm(list = ls());
data("airquality");

#help("airquality");


#+end_src

#+RESULTS:
: airquality


 - Use the help("airquality") command to find out about the data. Convert the values to m/s for wind speed and Celcius for temperature. Give a brief description of the data in your own words.

#+begin_src R :session Q1 :export code :results output
airquality$Wind <- airquality$Wind * 0.44704
airquality$Temp <- (airquality$Temp - 32) * 5/9

result <- data.frame(Wind = airquality$Wind, Temp = airquality$Temp)
#print(result)
#+end_src

#+RESULTS:

The ~airquality~ data set contains four measured values of the air quality in New York from May 1, 1973 to September 30, 1973.

 - Plot the daily temperature vs time, and the daily Solar.R through time, and comment on any trends or patterns you see.

#+begin_src R :export code :results output
rm(list = ls());
data("airquality")

airquality$Date <- as.Date(paste(1973, airquality$Month, airquality$Day, sep = "-"))
airquality$Wind <- airquality$Wind * 0.44704
airquality$Temp <- (airquality$Temp - 32) * 5/9

x11() # Change to windows(), for windows, or quartz(), for macOS, im using linux
plot(airquality$Date, airquality$Temp, type = "l", col = "blue",
     main = "Daily Average Temperature in New York (1973)",
     xlab = "Date", ylab = "Average Temperature (°C)")

x11() # Change to windows(), for windows, or quartz(), for macOS, im using linux
plot(airquality$Date, airquality$Solar.R, type = "l", col = "orange",
     main = "Daily Average Solar Radiation in New York (1973)",
     xlab = "Date", ylab = "Average Solar Radiation (Langley)")

#+end_src

#+RESULTS:

It appears that the temperature rises during the middle months, which would relate to summer in the New York. And the solar radiation appears to remain similar through out the data, with a little lower average in the latter months.


** Summarise the data

 - Calculate the mean, median, and variance of each variable. You may have to deal with missing values (look up how).
#+begin_src R :session Q2 :export code :results output
rm(list = ls());

data("airquality")

airquality$Temp <- (airquality$Temp - 32) * 5/9
airquality$Wind <- airquality$Wind * 0.44704

mean_temp <- mean(airquality$Temp, na.rm = TRUE)
median_temp <- median(airquality$Temp, na.rm = TRUE)
var_temp <- var(airquality$Temp, na.rm = TRUE)

mean_wind <- mean(airquality$Wind, na.rm = TRUE)
median_wind <- median(airquality$Wind, na.rm = TRUE)
var_wind <- var(airquality$Wind, na.rm = TRUE)

print(paste("Mean Temperature (°C):", mean_temp))
print(paste("Median Temperature (°C):", median_temp))
print(paste("Variance of Temperature (°C):", var_temp))

print(paste("Mean Wind Speed (m/s):", mean_wind))
print(paste("Median Wind Speed (m/s):", median_wind))
print(paste("Variance of Wind Speed (m/s):", var_wind))
#+end_src

#+RESULTS:
: [1] "Mean Temperature (°C): 25.4901960784314"
: [1] "Median Temperature (°C): 26.1111111111111"
: [1] "Variance of Temperature (°C): 27.651645453503"
: [1] "Mean Wind Speed (m/s): 4.45140810457516"
: [1] "Median Wind Speed (m/s): 4.336288"
: [1] "Variance of Wind Speed (m/s): 2.48038095815578"

 - Calculate the probability that the wind speed measured on any day will be above 5m/s. (Hint: the which command can be used to create a list of which values satisfy a particular condition, e.g. which(airquality$Temp < 20) and you can use the length command to see how long that list is.)
#+begin_src R :session Q2 :export code :results output
above_5ms <- which(airquality$Wind > 5)
prob_wind_above_5 <- length(above_5ms) / nrow(airquality)

print(paste("Probability that the wind speed is above 5 (m/s):", prob_wind_above_5))
#+end_src

#+RESULTS:
: [1] "Probability that the wind speed is above 5 (m/s): 0.34640522875817"

 - Calculate the conditional probability that the temperature will be below 25C wind speed is above 5m/s.
#+begin_src R :session Q2 :export code :results output
temp_below_25_given_wind_above_5 <- airquality$Temp < 25 & airquality$Wind > 5
conditional_prob <- sum(temp_below_25_given_wind_above_5, na.rm = TRUE) / length(above_5ms)

print(paste("P(T<25°C|W>5m/s):", conditional_prob))
#+end_src

#+RESULTS:
: [1] "P(T<25°C|W>5m/s) 0.547169811320755"

 - Do you think the two variables (Temp, Wind) are independent? Why / why not?
We can check the correlation coefficient:
#+begin_src R :session Q2 :export code :results output
correlation <- cor(airquality$Temp, airquality$Wind, use = "complete.obs")

print(paste("The correlation coefficient of the Temp and Wind:", correlation))
#+end_src

#+RESULTS:
: [1] "The correlation coefficient of the Temp and Wind: -0.457987879104833"

It is ~-0.46~, which is not particularly close to zero, so they are correlated.

** Correlations

 - Plot the airquality data as x-y plots with appropriate labels (title, axes). Note any obvious patterns about the data, e.g., correlations or trends.
    - Extension task: Find out how to fit a straight line to a set of bivariate data, and add that line to your plots. You may find the R commands abline and lm useful.
#+begin_src R :session Q3 :export code :results output
data("airquality")

airquality$Temp <- (airquality$Temp - 32) * 5/9
airquality$Wind <- airquality$Wind * 0.44704


x11() # Change to windows(), for windows, or quartz(), for macOS, im using linux
plot(airquality$Solar.R, airquality$Ozone,
     main = "Ozone vs. Solar Radiation",
     xlab = "Solar Radiation (Langley)",
     ylab = "Ozone (ppb)",
     pch = 19, col = "blue")
abline(lm(Ozone ~ Solar.R, data = airquality), col = "red")

x11() # Change to windows(), for windows, or quartz(), for macOS, im using linux
plot(airquality$Wind, airquality$Ozone,
     main = "Ozone vs. Wind Speed",
     xlab = "Wind Speed (m/s)",
     ylab = "Ozone (ppb)",
     pch = 19, col = "green")
abline(lm(Ozone ~ Wind, data = airquality), col = "red")

x11() # Change to windows(), for windows, or quartz(), for macOS, im using linux
plot(airquality$Temp, airquality$Ozone,
     main = "Ozone vs. Temperature",
     xlab = "Temperature (°C)",
     ylab = "Ozone (ppb)",
     pch = 19, col = "purple")
abline(lm(Ozone ~ Temp, data = airquality), col = "red")

par(mfrow = c(1, 1))
#+end_src

#+RESULTS:

From the plots we can notice that:
 1. As the solar radiation increase, so does the ozone
    - This is expected, because ozone can be created using UV light, which comes from the solar radiation
 2. As the wind speed increases, the ozone decreases
 3. As the temperature increases, so does the ozone

 - Calculate all the linear correlations between the four variables of interest using the cor command. You can find out how to invoke it with help(cor).
#+begin_src R :session Q3 :export code :results output
cor_matrix <- cor(airquality[, c("Ozone", "Solar.R", "Wind", "Temp")], use = "complete.obs")
print(cor_matrix)
#+end_src

#+RESULTS:
:          Ozone      Solar.R   Wind        Temp
: Ozone    1.0000000  0.3483417 -0.6124966  0.6985414
: Solar.R  0.3483417  1.0000000 -0.1271835  0.2940876
: Wind    -0.6124966 -0.1271835  1.0000000 -0.4971897
: Temp     0.6985414  0.2940876 -0.4971897  1.0000000


 - Use the cor.test command to calculate the p-values for these correlations. Remember that these p-values are a bit suspect (for reasons not yet covered in class) so should only be used as a guide. Are any of the relationships significant according to this test?
#+begin_src R :session Q3 :export code :results output
cor_test_results <- function(x, y) {
  test <- cor.test(x, y, use = "complete.obs")
  return(c(correlation = test$estimate, p.value = test$p.value))
}

p_values <- list(
  Ozone_Solar_R = cor_test_results(airquality$Ozone, airquality$Solar.R),
  Ozone_Wind = cor_test_results(airquality$Ozone, airquality$Wind),
  Ozone_Temp = cor_test_results(airquality$Ozone, airquality$Temp),
  Solar_R_Wind = cor_test_results(airquality$Solar.R, airquality$Wind),
  Solar_R_Temp = cor_test_results(airquality$Solar.R, airquality$Temp),
  Wind_Temp = cor_test_results(airquality$Wind, airquality$Temp)
)

print(p_values)
#+end_src

#+RESULTS:
#+begin_example
$Ozone_Solar_R
correlation.cor         p.value
   0.3483416930    0.0001793109

$Ozone_Wind
correlation.cor         p.value
  -6.015465e-01    9.271974e-13

$Ozone_Temp
correlation.cor         p.value
   6.983603e-01    2.931897e-18

$Solar_R_Wind
correlation.cor         p.value
    -0.05679167      0.49595521

$Solar_R_Temp
correlation.cor         p.value
   0.2758402713    0.0007517729

$Wind_Temp
correlation.cor         p.value
  -4.579879e-01    2.641597e-09
#+end_example

 - Which variable (Solar.R, Wind, Temp) do you think has the strongest effect on Ozone? Justify your answer.

** Distributions

 - Plot the distributions of each of the variables either with a histogram or a density (or both).
 - What distribution do you think best fits the temperature values? Why?
 - Describe the distribution of wind speed values: is it skewed? symmetric? normal?
 - Describe the distribution of wind speed values: is it skewed? symmetric? normal? Looks like a normal distribution or maybe a gamma distribution.
 - Overlay a plot of the normal distribution with mean and standard deviation equal to those of the wind speed values, over your plot of the wind speed. How well or badly does it fit? Do you maintain your position on whether the wind speed is normally distributed?
