:PROPERTIES:
:ID:       51f7c5ef-86da-44f3-8d30-b58e676628f3
:END:
#+title: ENG231 - Electrical Machines And Transformers - Assignment 2
#+date: [2024-10-05 Sat 11:01]
#+AUTHOR: Baley Eccles - 652137
#+FILETAGS: :Assignment:TODO:
#+STARTUP: latexpreview
#+LATEX_HEADER: \usepackage[a4paper, margin=2.5cm]{geometry}
#+LATEX_HEADER_EXTRA: \usepackage{minted}
#+LATEX_HEADER_EXTRA: \usepackage{fontspec}
#+LATEX_HEADER_EXTRA: \setmonofont{Iosevka}
#+LATEX_HEADER_EXTRA: \setminted{fontsize=\small, frame=single, breaklines=true}
#+LATEX_HEADER_EXTRA: \usemintedstyle{emacs}
#+LATEX_HEADER_EXTRA: \usepackage[backend=biber,style=apa]{biblatex}
#+LATEX_HEADER_EXTRA: \addbibresource{citation.bib}
#+LATEX_HEADER_EXTRA: \usepackage{float}


* ENG231 - Electrical Machines And Transformers - Assignment 2
** Part 1: Calculation of transformer winding voltages

#+BEGIN_SRC octave :exports both :results output :session Part1
h = 90 *10^(-2);
l = 130 *10^(-2);
d = 22 *10^(-2);
g = 1.8 *10^(-3);
mu0 = 4*pi*10^(-7);
mur = 1800;
A = d^2;
Np = 1360;
Ns = 315;
a=Ns/Np;
f = 50;
I = 3.3;

% Reluctance
%Rgap = g/(mu0*A);
%Rside = (h-2*d-g)/(mu0*mur*A);
%Rbottom = l/(mu0*mur*A);
%Rtop = l/(mu0*mur*A);
%R = 2*Rside + Rbottom + Rtop + 2*Rgap;


Rgap = g/(mu0*A);
RTopGap = (d/2)/(mu0*mur*A);
RTop = (l-d)/(mu0*mur*A);
Rheight = (h-d-g-d/2)/(mu0*mur*A);
RBottom = (l-d)/(mu0*mur*A);
R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;



Phi=(1/R)*Np*I;
V1 = 2*pi*Np*Phi*f/sqrt(2);
V2 = a*V1;

fprintf('Primary Voltage (V1): %.2f V (RMS)\n', V1);
fprintf('Secondary Voltage (V2): %.2f V (RMS)\n', V2);
#+END_SRC

#+RESULTS:
: Primary Voltage (V1): 14849.46 V (RMS)
: Secondary Voltage (V2): 3439.40 V (RMS)

** Part 2: Specification of transformer design to suit application
With the last digit of my student ID being 7:
| Student ID | Rated apparent  | Primary side rated  | Secondary side rated | 3-phase         |
| last digit | power (3-phase) | voltage (line-line) | voltage (line-line)  | connection type |
| 7          | 460 kVA         | 22 kV               | 400 V                | Δ-Y             |




#+BEGIN_SRC octave :exports code :results output :session Part2
clc
clear
close all

%VARIBLES
layersP = 1
layersS = 5
NPConst = 1000
g = 1*10.^-3
B = 1.6


h = 1;
d = 0.5;

Vp = 22*10.^3;
Vs = 400;

a = Vs / (Vp*sqrt(3));
NP = layersP*NPConst;
NS = a*NP;
WindingsPerLayerP = NP./layersP;
WindingsPerLayerS = NS./layersS;

S = 460*10.^3;

Ip = S/(sqrt(3)*Vp)
Is = S/(sqrt(3)*Vs)

%TotalIp = S./(sqrt(3)*Vp)
%IPerLayerP = TotalIp./layersP
%TotalIs = S./(sqrt(3)*Vs)
%IPerLayerS = TotalIs./layersS
%
%IpMax = 0.05*IPerLayerP
%IsMax = 0.05*IPerLayerS

%This allows us to choose a wire size for each side.
WireDiamP = 2.03 *10.^-3;
WireDiamS = 2.03 *10.^-3;

%Choosing the wire size allows us to calculate the required gap between the wires.
GapWireMin = max([WireDiamP*layersP*2, WireDiamS*layersS*2]);

f = 50;
mur = 2150;
mu0=4*pi*10.^(-7);
mu = mu0*mur


A = d.^2;
Phi=B*A;

% These two must be the same
R = NP*(Ip/sqrt(3))./Phi
R = NS*Is./Phi



%l = d + (mu0.*mur.*A./2)*(R-2.*g./(mu0.*A));
l = A.*mu0.*mur.*(2.*g ./ (A.*mu0) + d./ (A.*mu0.*mur) - R - 3.*d ./ (A.*mu0.*mur) - 2.*d ./ (A.*mu0.*mur)) ./ -2;

l = ((A*R*mu0*mur)/2)+2*d-g*mur+g-h

GapWireReal = l-2*d-WireDiamP*layersP-WireDiamS*layersS

if GapWireReal < GapWireMin
  fprintf("The gap is too small, a lenght of %f is too small", l)
endif
%VTop = d.*d.*l;
%VBottom = VTop;
%VSide = (h-d-d-g).*d.*d;
%Volume = VTop + VBottom + 2.*VSide;
%Volume(Volume<0) = [];
%[minVol, minIndex] = min(A);

%Volume(minIndex)
l
h
d
NP
NS
Ip
#+END_SRC
#+RESULTS:
#+begin_example
layersP = 1
layersS = 5
NPConst = 1000
g = 1.0000e-03
B = 1.6000
Ip = 12.072
Is = 663.95
mu = 2.7018e-03
R = 1.7424e+04
R = 1.7424e+04
l = 3.7355
GapWireReal = 2.7234
l = 3.7355
h = 1
d = 0.5000
NP = 1000
NS = 10.497
Ip = 12.072
#+end_example

#+BEGIN_SRC octave :exports both :results output :session Verification
h = 1;
l = 3.7355;
d = 3;
g = 1*10^(-3);
mu0 = 4*pi*10^(-7);
mur = 2150;
A = d^2;
Np = 1000;
Ns = 10.497;
a=Ns/Np;
f = 50;
I = 12.072/sqrt(3);

% Reluctance

Rgap = g/(mu0*A);
RTopGap = (d/2)/(mu0*mur*A);
RTop = (l-d)/(mu0*mur*A);
Rheight = (h-d-g-d/2)/(mu0*mur*A);
RBottom = (l-d)/(mu0*mur*A);
R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;


Phi=(1/R)*Np*I;
V1 = 2*pi*Np*Phi*f/sqrt(2);
V2 = a*V1;

fprintf('Primary Voltage (V1): %.2f V (RMS)\n', V1);
fprintf('Secondary Voltage (V2): %.2f V (RMS)\n', V2);

#+END_SRC

#+RESULTS:
: Primary Voltage (V1): 21282197.77 V (RMS)
: Secondary Voltage (V2): 223399.23 V (RMS)

#+BEGIN_SRC octave :exports both :results output :session Part2At2
h = 2;
l = 2;
g = 10^-3;
mu0 = 4*pi*10^(-7);
mur = 2150;
f = 50;
B = 1.6;
% Finding the secondary windings based on the voltages
Np = 1000;
Vp = 22*10^3;
Vs = 400;
a = Vs/(Vp*sqrt(3))
Ns = Np*a



% Finding the current based on the rated power
S = 460*10^6;

Is = S/Vs;
Ip = (Is/sqrt(3))*a;

% Rearanging the reluctance equation and the flux equation allows us to find an expression for d

d = g*mur/2 - g/2 + h/2 + l/2 - Ip*Np*mu0*mur/(4*B)


#+END_SRC

#+RESULTS:
: a = 0.010497
: Ns = 10.497
: Vp = 3.8105e+04
: d = -2939.2



** Part 3: Discussion about transformer design trade-offs
 - Describe the influence that your winding design choices (number of turns and layers) have on transformer size and mass? How might you design for minimum total mass, and what trade-off do you see between iron core mass and copper mass?

To minimise volume/mass we can choose values:
 - Volume = 20.363
 - Length = 1018.3
 - height = 0.1000
 - depth  = 0.1000
However this is obviously not good, as the length is over 1km long.
 - Discuss how maximum operating core flux density impacts the required magnetising current and transformer mass?
 - Calculate, by adding to your code, the winding losses for your transformer (calculated power loss at rated operation, as a % of rated throughput power)? You may assume that the AC resistance in normal operation is 20% larger than the calculated DC resistance (owing to skin effect and elevated temperatures). Discuss how transformer design influences this loss?
 - What aspects of the transformer design (size and mass) or operation (magnetising current, losses) are influenced by core gap width for this transformer?
 - For a power transformer, the main components which influence how it impacts the power system are generally the winding resistance and the leakage reactance. Comment on how you think your design choices, in particular the way you have configured each winding, will influence these parameters?
