:PROPERTIES:
:ID:       51f7c5ef-86da-44f3-8d30-b58e676628f3
:END:
#+title: ENG231 - Electrical Machines And Transformers - Assignment 2
#+date: [2024-10-05 Sat 11:01]
#+AUTHOR: Baley Eccles - 652137
#+FILETAGS: :Assignment:TODO:
#+STARTUP: latexpreview
#+LATEX_HEADER: \usepackage[a4paper, margin=2.5cm]{geometry}
#+LATEX_HEADER_EXTRA: \usepackage{minted}
#+LATEX_HEADER_EXTRA: \usepackage{fontspec}
#+LATEX_HEADER_EXTRA: \setmonofont{Iosevka}
#+LATEX_HEADER_EXTRA: \setminted{fontsize=\small, frame=single, breaklines=true}
#+LATEX_HEADER_EXTRA: \usemintedstyle{emacs}
#+LATEX_HEADER_EXTRA: \usepackage[backend=biber,style=apa]{biblatex}
#+LATEX_HEADER_EXTRA: \addbibresource{citation.bib}
#+LATEX_HEADER_EXTRA: \usepackage{float}


* ENG231 - Electrical Machines And Transformers - Assignment 2
** Part 1: Calculation of transformer winding voltages

#+BEGIN_SRC octave :exports both :results output :session Part1
h = 90 *10^(-2);
l = 130 *10^(-2);
d = 22 *10^(-2);
g = 1.8 *10^(-3);
mu0 = 4*pi*10^(-7);
mur = 1800;
A = d^2;
Np = 1360;
Ns = 315;
a=Ns/Np;
f = 50;
I = 3.3;

% Reluctance
%Rgap = g/(mu0*A);
%Rside = (h-2*d-g)/(mu0*mur*A);
%Rbottom = l/(mu0*mur*A);
%Rtop = l/(mu0*mur*A);
%R = 2*Rside + Rbottom + Rtop + 2*Rgap;


Rgap = g/(mu0*A);
RTopGap = (d/2)/(mu0*mur*A);
RTop = (l-d)/(mu0*mur*A);
Rheight = (h-d-g-d/2)/(mu0*mur*A);
RBottom = (l-d)/(mu0*mur*A);
R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;



Phi=(1/R)*Np*I;
V1 = 2*pi*Np*Phi*f/sqrt(2);
V2 = a*V1;

fprintf('Primary Voltage (V1): %.2f V (RMS)\n', V1);
fprintf('Secondary Voltage (V2): %.2f V (RMS)\n', V2);
#+END_SRC

#+RESULTS:
: Primary Voltage (V1): 14849.46 V (RMS)
: Secondary Voltage (V2): 3439.40 V (RMS)

** Part 2: Specification of transformer design to suit application
With the last digit of my student ID being 7:
| Student ID | Rated apparent  | Primary side rated  | Secondary side rated | 3-phase         |
| last digit | power (3-phase) | voltage (line-line) | voltage (line-line)  | connection type |
| 7          | 460 kVA         | 22 kV               | 400 V                | $\Delta$-Y     |



#+BEGIN_SRC octave :exports code :results output :session Part2
clc
clear
close all

% Turns
VpLineToLineRMS = 22*10^3;
VsLineToLineRMS = 400;
VpLineToLinePeak = sqrt(2)*VpLineToLineRMS;
VsLineToLinePeak = sqrt(2)*VsLineToLineRMS;

a = VsLineToLineRMS/(sqrt(3)*VpLineToLineRMS)

NpLayers = 1;
Np = 1000/NpLayers;
NsLayers = 2;
Ns = Np*a/NsLayers;

% Currnet
S = (460*10^3)/3;
IpLineRMS = S/(sqrt(3)*VpLineToLineRMS)
IpLinePerLayerRMS = IpLineRMS/NpLayers;
IsRMS = IpLineRMS/(a)
IsLinePerLayerRMS = IsRMS/NsLayers;



% Flux
f = 50;
Phi = (VpLineToLineRMS)/(4.44*Np*f) % These may be wrong I am unsure where the sqrt(3) goes.
Phi = (VsLineToLineRMS/sqrt(3))/(4.44*Ns*f)

% Relucatance
R = (1/Phi)*Np*IpLineRMS
R = (1/Phi)*Ns*IsRMS


mu0 = 4*pi*10^(-7);
mur = 2150;
mu = mu0*mur;

g = 10^-3;
% Dimensions
d = 0.5
h = 0.2
l = d.*mu.*(2.*g ./ (d.*mu0) + 1 ./ mu + 2.*h ./ (d.*mu) - R.*d - 3 ./ mu - 2.*g ./ (d.*mu) - 2 ./ mu) ./ -2

% Choosing a Wire Diameter
wireDiameters = [2.03, 2.34, 2.64, 2.95, 3.25, 3.66, 4.06, 4.47, 4.88, 5.39, 5.89, 6.40, 7.01, 7.62, 8.23, 8.84, 9.5, 10.2, 11.0, 11.8, 12.7, 15.0, 17.0, 20.0, 22.0, 24.0, 28.0, 31.0, 34.0, 37.0, 39.0, 41.0] * 10^-3;
maxCurrentRMS = [8.3, 10.5, 13.5, 16.6, 21.2, 26.5, 33.3, 44.2, 52.3, 63.8, 76.4, 90.1, 108, 128, 149, 172, 196, 227, 265, 306, 355, 495, 636, 880, 1064, 1267, 1724, 2113, 2542, 3011, 3345, 3697];

IpMax = 0.05*IpLinePerLayerRMS;
IsMax = 0.05*IsLinePerLayerRMS;

indexPrimary = find(maxCurrentRMS >= IpMax, 1);
wireDiameterP = wireDiameters(indexPrimary);
indexSecondary = find(maxCurrentRMS >= IsMax, 1);
wireDiameterS = wireDiameters(indexSecondary);

% Verify that the transformer is conformant with the required specifications
if (Phi/(d^2) > 1.6)
  sprintf("Flux is too big");
endif
gapSize = l-d-d-NpLayers*wireDiameterP-NsLayers*wireDiameterS;
gapSizeMin = max([2*NpLayers*wireDiameterP, 2*NsLayers*wireDiameterS]);
if (gapSize < gapSizeMin)
  sprintf("The gap is not big enough");
endif
#+END_SRC

#+RESULTS:
#+begin_example
a = 0.010497
IpLineRMS = 4.0240
IsRMS = 383.33
Phi = 0.099099
Phi = 0.1982
R = 2.0303e+04
R = 1.0151e+04
d = 0.5000
h = 0.2000
l = 2.0793
IpMax = 0.2012
IsMax = 9.5833
wireDiameterP = 2.0300e-03
wireDiameterS = 2.3400e-03
#+end_example




#+BEGIN_SRC octave :exports none :results output :session Verification
h = 4;
l = 2.1942*10^8;
d = 2000;
g = 1*10^(-3);
mu0 = 4*pi*10^(-7);
mur = 2150;
A = d^2;
Np = 1000;
Ns = 10.497;
a=Ns/Np;
f = 50;
Ip = 4.0240;

Rgap = g/(mu0*A);
RTopGap = (d/2)/(mu0*mur*A);
RTop = (l-d)/(mu0*mur*A);
Rheight = (h-d-g-d/2)/(mu0*mur*A);
RBottom = (l-d)/(mu0*mur*A);
R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;

Phi=(1/R)*Np*Ip;
Vp = 2*pi*Np*Phi*f/sqrt(2);
Vs = a*Vp*sqrt(3);

fprintf('Primary Voltage (Vp): %.2f V (RMS)\n', Vp);
fprintf('Secondary Voltage (Vs): %.2f V (RMS)\n', Vs);
#+END_SRC

#+RESULTS:
: B = 2.4775e-08
: Primary Voltage (Vp): 22014.20 V (RMS)
: Secondary Voltage (Vs): 400.25 V (RMS)


#+BEGIN_SRC octave :exports code :results output :session Part2Function
clc
clear
close all



NpLayersArray = 1:10;
NpCountArray = 100:10:10000;
NsLayersArray = 1:10;
gArray = 10^-3:10^-5:3*10^-3;
dArray = 0:0.01:10;
hArray = 0:0.01:10;

results = [];
for NpLayers = NpLayersArray
  for NpCount = NpCountArray
    for NsLayers = NsLayersArray
      for g = gArray
        for d = dArray
          for h = hArray
            [output] = Transformer(NpLayers, NpCount, NsLayers, g, d, h);
            results = [results; output];
          end
        end
      end
    end
  end
end
function output = Transformer (NpLayers, NpCount, NsLayers, g, d, h)
                                % Constatans
  VpLineToLineRMS = 22*10^3;
  VsLineToLineRMS = 400;
  VpLineToLinePeak = sqrt(2)*VpLineToLineRMS;
  VsLineToLinePeak = sqrt(2)*VsLineToLineRMS;
  a = VsLineToLineRMS/(sqrt(3)*VpLineToLineRMS);
  S = (460*10^3)/3;
  f = 50;
  mu0 = 4*pi*10^(-7);
  mur = 2150;
  mu = mu0*mur;

  Np = NpCount/NpLayers;
  Ns = Np*a/NsLayers;
                                % Currnet
  IpLineRMS = S/(sqrt(3)*VpLineToLineRMS)
  IpLinePerLayerRMS = IpLineRMS/NpLayers;
  IsRMS = IpLineRMS/(a);
  IsLinePerLayerRMS = IsRMS/NsLayers;
                                    % Flux
  Phi = (VpLineToLineRMS)/(4.44*Np*f);
  Phi = (VsLineToLineRMS/sqrt(3))/(4.44*Ns*f);
                                % Relucatance
  R = (1/Phi)*Np*IpLineRMS;
  R = (1/Phi)*Ns*IsRMS;
                                % Dimensions
  l = d.*mu.*(2.*g ./ (d.*mu0) + 1 ./ mu + 2.*h ./ (d.*mu) - R.*d - 3 ./ mu - 2.*g ./ (d.*mu) - 2 ./ mu) ./ -2;
                                % Choosing a Wire Diameter
  wireDiameters = [2.03, 2.34, 2.64, 2.95, 3.25, 3.66, 4.06, 4.47, 4.88, 5.39, 5.89, 6.40, 7.01, 7.62, 8.23, 8.84, 9.5, 10.2, 11.0, 11.8, 12.7, 15.0, 17.0, 20.0, 22.0, 24.0, 28.0, 31.0, 34.0, 37.0, 39.0, 41.0] * 10^-3;
  maxCurrentRMS = [8.3, 10.5, 13.5, 16.6, 21.2, 26.5, 33.3, 44.2, 52.3, 63.8, 76.4, 90.1, 108, 128, 149, 172, 196, 227, 265, 306, 355, 495, 636, 880, 1064, 1267, 1724, 2113, 2542, 3011, 3345, 3697];
  IpMax = 0.05*IpLinePerLayerRMS;
  IsMax = 0.05*IsLinePerLayerRMS;
  indexPrimary = find(maxCurrentRMS >= IpMax, 1);
  wireDiameterP = wireDiameters(indexPrimary);
  indexSecondary = find(maxCurrentRMS >= IsMax, 1);
  wireDiameterS = wireDiameters(indexSecondary);
  % Verify that the transformer is conformant with the required specifications
  if (Phi/(d^2) > 1.6)
    sprintf("Flux is too big");
  endif
  gapSize = l-d-d-NpLayers*wireDiameterP-NsLayers*wireDiameterS;
  gapSizeMin = max([2*NpLayers*wireDiameterP, 2*NsLayers*wireDiameterS]);
  if (gapSize < gapSizeMin)
    sprintf("The gap is not big enough");
  endif
  output = struct('NpLayers', NpLayers, 'NpCount', NpCount, 'NsLayers', NsLayers, 'g', g, 'd', d, 'h', h);
endfunction
#+END_SRC

#+RESULTS:
: error: 'a' undefined near line 3, column 11
: error: called from
:     Transformer at line 3 column 6

** Part 3: Discussion about transformer design trade-offs
 - Describe the influence that your winding design choices (number of turns and layers) have on transformer size and mass? How might you design for minimum total mass, and what trade-off do you see between iron core mass and copper mass?

However this is obviously not good, as the length is over 1km long.
 - Discuss how maximum operating core flux density impacts the required magnetising current and transformer mass?
 - Calculate, by adding to your code, the winding losses for your transformer (calculated power loss at rated operation, as a % of rated throughput power)? You may assume that the AC resistance in normal operation is 20% larger than the calculated DC resistance (owing to skin effect and elevated temperatures). Discuss how transformer design influences this loss?
 - What aspects of the transformer design (size and mass) or operation (magnetising current, losses) are influenced by core gap width for this transformer?
 - For a power transformer, the main components which influence how it impacts the power system are generally the winding resistance and the leakage reactance. Comment on how you think your design choices, in particular the way you have configured each winding, will influence these parameters?
