:PROPERTIES:
:ID:       51f7c5ef-86da-44f3-8d30-b58e676628f3
:END:
#+title: ENG231 - Electrical Machines And Transformers - Assignment 2
#+date: [2024-10-05 Sat 11:01]
#+AUTHOR: Baley Eccles - 652137
#+FILETAGS: :Assignment:TODO:
#+STARTUP: latexpreview
#+LATEX_HEADER: \usepackage[a4paper, margin=2.5cm]{geometry}
#+LATEX_HEADER_EXTRA: \usepackage{minted}
#+LATEX_HEADER_EXTRA: \usepackage{fontspec}
#+LATEX_HEADER_EXTRA: \setmonofont{Iosevka}
#+LATEX_HEADER_EXTRA: \setminted{fontsize=\small, frame=single, breaklines=true}
#+LATEX_HEADER_EXTRA: \usemintedstyle{emacs}
#+LATEX_HEADER_EXTRA: \usepackage[backend=biber,style=apa]{biblatex}
#+LATEX_HEADER_EXTRA: \addbibresource{citation.bib}
#+LATEX_HEADER_EXTRA: \usepackage{float}


* ENG231 - Electrical Machines And Transformers - Assignment 2
** Part 1: Calculation of transformer winding voltages
|---------------+-------------+---------------+-------------|
| Wire Diameter | Maximum RMS | Wire Diameter | Maximum RMS |
|          (mm) | current (A) |          (mm) | current (A) |
|---------------+-------------+---------------+-------------|
|          2.03 |         8.3 |           9.5 |         196 |
|          2.34 |        10.5 |          10.2 |         227 |
|          2.64 |        13.5 |          11.0 |         265 |
|          2.95 |        16.6 |          11.8 |         306 |
|          3.25 |        21.2 |          12.7 |         355 |
|          3.66 |        26.5 |          15.0 |         495 |
|          4.06 |        33.3 |          17.0 |         636 |
|          4.47 |        44.2 |          20.0 |         880 |
|          4.88 |        52.3 |          22.0 |        1064 |
|          5.39 |        63.8 |          24.0 |        1267 |
|          5.89 |        76.4 |          28.0 |        1724 |
|          6.40 |        90.1 |          31.0 |        2113 |
|          7.01 |         108 |          34.0 |        2542 |
|          7.62 |         128 |          37.0 |        3011 |
|          8.23 |         149 |          39.0 |        3345 |
|          8.84 |         172 |          41.0 |        3697 |
|---------------+-------------+---------------+-------------|

#+BEGIN_SRC octave :exports both :results output :session Part1
h = 90 *10^(-2);
l = 130 *10^(-2);
d = 22 *10^(-2);
g = 1.8 *10^(-3);
mu0 = 4*pi*10^(-7);
mur = 1800;
A = d^2;
Np = 1360;
Ns = 315;
a=Ns/Np;
f = 50;
I = 3.3;

% Reluctance
Rgap = g/(mu0*A);
Rside = (h-2*l-g)/(mu0*mur*A);
Rbottom = l/(mu0*mur*A);
Rtop = l/(mu0*mur*A);
R = 2*Rside + Rbottom + Rtop + 2*Rgap;



Phi=(1/R)*Np*I;
V1 = 4.44*pi*Phi*f;
V2 = a*V1;

fprintf('Primary Voltage (V1): %.2f V (RMS)\n', V1);
fprintf('Secondary Voltage (V2): %.2f V (RMS)\n', V2);
#+END_SRC

#+RESULTS:
: Primary Voltage (V1): 60.37 V (RMS)
: Secondary Voltage (V2): 13.98 V (RMS)

** Part 2: Specification of transformer design to suit application
With the last digit of my student ID being 7:
| Student ID | Rated apparent  | Primary side rated  | Secondary side rated | 3-phase         |
| last digit | power (3-phase) | voltage (line-line) | voltage (line-line)  | connection type |
| 7          | 460 kVA         | 22 kV               | 400 V                | Δ-Y             |




#+BEGIN_SRC octave :exports code :results output :session Part2
clc
clear
close all


%VARIBLES

layersP = 1
layersS = 5
NPConst = 1000
g = 1*10.^-3
B=1.6

h = 2;
d = 2.5;

h = 0.1:0.1:10;
d = 0.1:0.1:10;

a=400./(22*10.^3);
NP = layersP*NPConst
NS = a*NP
WindingsPerLayerS = NS./layersS



S = 460*10.^3;
Vp = 22*10.^3;
Vs = 400;

Ip = S./(sqrt(3)*Vp);
IPerLayerP = Ip./layersP;
Is = S./(sqrt(3)*Vs);
IPerLayerS = Is./layersS;

IpMax = 0.05*IPerLayerP
IsMax = 0.05*IPerLayerS

%This allows us to choose a wire size for each side.
WireDiamP = 2.03 *10.^-3;
WireDiamS = 2.03 *10.^-3;

%Choosing the wire size allows us to calculate the required gap between the wires.
GapWire = WireDiamP*layersP*2;

f = 50;
S = 460*10.^3;
Vp = 22*10.^3;
Vs = 400;
mur = 2150;
mu0=4*pi*10.^(-7);
mu = mu0*mur


A = d.^2;
Phi=B*A;

% These two must be the same
R = NP*Ip./Phi;
R = NS*Is./Phi;

l=(mu*(R-2*((h-d)./mu)-g./mu0)./2)+d;

Volume = 2.*(((mu.*(R-2.*((h-d)./mu)-g./mu0)./2)+d).*d.*d)+2.*((h-d-d).*d.*d);
Volume(Volume<0) = [];
[minVol, minIndex] = min(A);

Volume(minIndex)
l(minIndex)
h(minIndex)
d(minIndex)
#+END_SRC

#+RESULTS:
#+begin_example
layersP = 1
layersS = 5
NPConst = 1000
g = 1.0000e-03
B = 1.6000
NP = 1000
NS = 18.182
WindingsPerLayerS = 3.6364
IpMax = 0.6036
IsMax = 6.6395
mu = 2.7018e-03
ans = 20.363
ans = 1018.3
ans = 0.1000
ans = 0.1000
#+end_example

To minimise volume we can choose values:
Volume = 20.363\\
Length = 1018.3\\
height = 0.1000\\
depth  = 0.1000\\
** Part 3: Discussion about transformer design trade-offs
 - Describe the influence that your winding design choices (number of turns and layers) have on transformer size and mass? How might you design for minimum total mass, and what trade-off do you see between iron core mass and copper mass?

To minimise volume/mass we can choose values:
 - Volume = 20.363
 - Length = 1018.3
 - height = 0.1000
 - depth  = 0.1000
However this is obviously not good, as the length is over 1km long.
 - Discuss how maximum operating core flux density impacts the required magnetising current and transformer mass?
 - Calculate, by adding to your code, the winding losses for your transformer (calculated power loss at rated operation, as a % of rated throughput power)? You may assume that the AC resistance in normal operation is 20% larger than the calculated DC resistance (owing to skin effect and elevated temperatures). Discuss how transformer design influences this loss?
 - What aspects of the transformer design (size and mass) or operation (magnetising current, losses) are influenced by core gap width for this transformer?
 - For a power transformer, the main components which influence how it impacts the power system are generally the winding resistance and the leakage reactance. Comment on how you think your design choices, in particular the way you have configured each winding, will influence these parameters?
