:PROPERTIES:
:ID:       51f7c5ef-86da-44f3-8d30-b58e676628f3
:END:
#+title: ENG231 - Electrical Machines And Transformers - Assignment 2
#+date: [2024-10-05 Sat 11:01]
#+AUTHOR: Baley Eccles - 652137
#+FILETAGS: :Assignment:TODO:UTAS:2024:
#+STARTUP: latexpreview
#+LATEX_HEADER: \usepackage[a4paper, margin=2.5cm]{geometry}
#+LATEX_HEADER_EXTRA: \usepackage{minted}
#+LATEX_HEADER_EXTRA: \usepackage{fontspec}
#+LATEX_HEADER_EXTRA: \setmonofont{Iosevka}
#+LATEX_HEADER_EXTRA: \setminted{fontsize=\small, frame=single, breaklines=true}
#+LATEX_HEADER_EXTRA: \usemintedstyle{emacs}
#+LATEX_HEADER_EXTRA: \usepackage[backend=biber,style=apa]{biblatex}
#+LATEX_HEADER_EXTRA: \addbibresource{citation.bib}
#+LATEX_HEADER_EXTRA: \usepackage{float}


* ENG231 - Electrical Machines And Transformers - Assignment 2
** Part 1: Calculation of transformer winding voltages
  :PROPERTIES:
  :ID: ENG231 - Electrical Machines And Transformers - Assignment 2 - Part 1: Calculation of transformer winding voltages
  :END:
#+BEGIN_SRC octave :exports both :results output :session Part1
h = 90 *10^(-2);
l = 130 *10^(-2);
d = 22 *10^(-2);
g = 1.8 *10^(-3);
mu0 = 4*pi*10^(-7);
mur = 1800;
A = d^2;
Np = 1360;
Ns = 315;
a=Ns/Np;
f = 50;
I = 3.3;

% Reluctance
%Rgap = g/(mu0*A);
%Rside = (h-2*d-g)/(mu0*mur*A);
%Rbottom = l/(mu0*mur*A);
%Rtop = l/(mu0*mur*A);
%R = 2*Rside + Rbottom + Rtop + 2*Rgap;


Rgap = g/(mu0*A);
RTopGap = (d/2)/(mu0*mur*A);
RTop = (l-d)/(mu0*mur*A);
Rheight = (h-d-g-d/2)/(mu0*mur*A);
RBottom = (l-d)/(mu0*mur*A);
R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;



Phi=(1/R)*Np*I;
V1 = 2*pi*Np*Phi*f/sqrt(2);
V2 = a*V1;

fprintf('Primary Voltage (V1): %.2f V (RMS)\n', V1);
fprintf('Secondary Voltage (V2): %.2f V (RMS)\n', V2);
#+END_SRC

#+RESULTS:
: Primary Voltage (V1): 14849.46 V (RMS)
: Secondary Voltage (V2): 3439.40 V (RMS)

** Part 2: Specification of transformer design to suit application
With the last digit of my student ID being 7:
| Student ID | Rated apparent  | Primary side rated  | Secondary side rated | 3-phase         |
| last digit | power (3-phase) | voltage (line-line) | voltage (line-line)  | connection type |
| 7          | 460 kVA         | 22 kV               | 400 V                | $\Delta$-Y     |


We know the voltages and the connection type, this means that we can calculate the turns ratio:
\[a = \frac{V_{secondary}}{\sqrt{3}V_{primary}}\]
#+BEGIN_SRC octave :exports code :results output :session Part2
clc
clear
close all

VpLineToLineRMS = 22*10^3;
VsLineToLineRMS = 400;
VpLineToLinePeak = sqrt(2)*VpLineToLineRMS;
VsLineToLinePeak = sqrt(2)*VsLineToLineRMS;
a = VsLineToLineRMS/(sqrt(3)*VpLineToLineRMS)
#+END_SRC

#+RESULTS:
: a = 0.010497

Now that we know the turns ratio, we can find specify the layers for both sides and the turns for one side and calculate the other side required turns:
\[a = \frac{N_{secondary}}{N_{primary}}\]
#+BEGIN_SRC octave :exports code :results output :session Part2 :TODO: There is somthing wrong with how the layers are being handled
NpLayers = 1;
Np = 1000/NpLayers
NsLayers = 2;
Ns = Np*a/NsLayers

#+END_SRC

#+RESULTS:
: Np = 1000
: Ns = 5.2486

We also know the max complex power for the three total transformers, by dividing by three we can find the per transformer rating. And with the following equation we can calculate the required current, noting that we have to divide by $\sqrt{3}$ for the primary side, as its $\Delta$ connected.
\[I = \frac{S}{V}\]
#+BEGIN_SRC octave :exports code :results output :session Part2
S = (460*10^3)/3;
IpLineRMS = S/(sqrt(3)*VpLineToLineRMS)
IpLinePerLayerRMS = IpLineRMS/NpLayers;
IsRMS = IpLineRMS/(a)
IsLinePerLayerRMS = IsRMS/NsLayers;
#+END_SRC

#+RESULTS:
: IpLineRMS = 4.0240
: IsRMS = 383.33


Now that we know the current we can find the smallest diameter wiring for our transformer.
#+BEGIN_SRC octave :exports code :results output :session Part2
wireDiameters = [2.03, 2.34, 2.64, 2.95, 3.25, 3.66, 4.06, 4.47, 4.88, 5.39, 5.89, 6.40, 7.01, 7.62, 8.23, 8.84, 9.5, 10.2, 11.0, 11.8, 12.7, 15.0, 17.0, 20.0, 22.0, 24.0, 28.0, 31.0, 34.0, 37.0, 39.0, 41.0] * 10^-3;
maxCurrentRMS = [8.3, 10.5, 13.5, 16.6, 21.2, 26.5, 33.3, 44.2, 52.3, 63.8, 76.4, 90.1, 108, 128, 149, 172, 196, 227, 265, 306, 355, 495, 636, 880, 1064, 1267, 1724, 2113, 2542, 3011, 3345, 3697];

IpMax = 0.05*IpLinePerLayerRMS;
IsMax = 0.05*IsLinePerLayerRMS;

indexPrimary = find(maxCurrentRMS >= IpMax, 1);
wireDiameterP = wireDiameters(indexPrimary)
indexSecondary = find(maxCurrentRMS >= IsMax, 1);
wireDiameterS = wireDiameters(indexSecondary)
#+END_SRC

#+RESULTS:
: wireDiameterP = 2.0300e-03
: wireDiameterS = 2.3400e-03


From here we can specify a magnetic flux density to be used, which can allow us to find the cross sectional and magnetic flux, using the two following equations.
\[\mathcal{E} = \frac{2\pi}{\sqrt{2}}Nf\Phi\]
\[\Phi = B\cdot A\]
#+BEGIN_SRC octave :exports code :results output :session Part2
B = 1.6;
f = 50;
A = ((VpLineToLineRMS)/(4.44*Np*f))/B
A = ((VsLineToLineRMS/sqrt(3))/(4.44*Ns*f))/B
d = sqrt(A)
Phi = B*A;
#+END_SRC

#+RESULTS:
: A = 0.061937
: A = 0.1239
: d = 0.3520

Next we can find the required reluctance using:
\[\Phi = \frac{Ni}{\mathfrak{R}}\]
#+BEGIN_SRC octave :exports code :results output :session Part2
R = (1/Phi)*Np*IpLineRMS
R = (1/Phi)*Ns*IsRMS
#+END_SRC

#+RESULTS:
: R = 2.0303e+04
: R = 1.0151e+04

Now knowing the reluctance we can choose a height and gap size and rearrange the equation from [[id:ENG231 - Electrical Machines And Transformers - Assignment 2 - Part 1: Calculation of transformer winding voltages][Part 1]] for length. This will result in a transformer that meets the voltage and power requirements.
#+BEGIN_SRC octave :exports code :results output :session Part2
mu0 = 4*pi*10^(-7);
mur = 2150;
mu = mu0*mur;
g = 10^-3;
h = 0.2
l = d.*mu.*(2.*g ./ (d.*mu0) + 1 ./ mu + 2.*h ./ (d.*mu) - R.*d - 3 ./ mu - 2.*g ./ (d.*mu) - 2 ./ mu) ./ -2
#+END_SRC

#+RESULTS:
: h = 0.2000
: l = 0.053634

How ever, this does not take into account the required gap between the windings in the middle. So, we can add a check that throws an error if the gap is not big enough.
#+BEGIN_SRC octave :exports code :results output :session Part2
gapSize = l-d-d-NpLayers*wireDiameterP-NsLayers*wireDiameterS;
gapSizeMin = max([2*NpLayers*wireDiameterP, 2*NsLayers*wireDiameterS]);
if (gapSize < gapSizeMin)
  sprintf("The gap is not big enough");
endif

IpLineRMS

Ns
Np

#+END_SRC

#+RESULTS:
: IpLineRMS = 4.0240
: Ns = 5.2486
: Np = 1000


Various outputs from the sets of code above was checked with the code from [[id:ENG231 - Electrical Machines And Transformers - Assignment 2 - Part 1: Calculation of transformer winding voltages][Part 1]] and the out put satisfied all of the required specifications.

#+BEGIN_SRC octave :exports none :results output :session Verification
h = 0.2;
l = 0.053634;
d = 0.3520;
g = 1*10^(-3);
mu0 = 4*pi*10^(-7);
mur = 2150;
A = d^2;
Np = 1000;
Ns = 5.25;
a=Ns/Np;
f = 50;
Ip = 4.0240;

Rgap = g/(mu0*A);
RTopGap = (d/2)/(mu0*mur*A);
RTop = (l-d)/(mu0*mur*A);
Rheight = (h-d-g-d/2)/(mu0*mur*A);
RBottom = (l-d)/(mu0*mur*A);
R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;

Phi=(1/R)*Np*Ip;
Vp = 2*pi*Np*Phi*f/sqrt(2);
Vs = a*Vp*sqrt(3);

fprintf('Primary Voltage (Vp): %.2f V (RMS)\n', Vp);
fprintf('Secondary Voltage (Vs): %.2f V (RMS)\n', Vs);
#+END_SRC

#+RESULTS:
: Primary Voltage (Vp): 88083.93 V (RMS)
: Secondary Voltage (Vs): 800.97 V (RMS)




** Part 3: Discussion about transformer design trade-offs
 - Describe the influence that your winding design choices (number of turns and layers) have on transformer size and mass? How might you design for minimum total mass, and what trade-off do you see between iron core mass and copper mass?

However this is obviously not good, as the length is over 1km long.
 - Discuss how maximum operating core flux density impacts the required magnetising current and transformer mass?
 - Calculate, by adding to your code, the winding losses for your transformer (calculated power loss at rated operation, as a % of rated throughput power)? You may assume that the AC resistance in normal operation is 20% larger than the calculated DC resistance (owing to skin effect and elevated temperatures). Discuss how transformer design influences this loss?
 - What aspects of the transformer design (size and mass) or operation (magnetising current, losses) are influenced by core gap width for this transformer?
 - For a power transformer, the main components which influence how it impacts the power system are generally the winding resistance and the leakage reactance. Comment on how you think your design choices, in particular the way you have configured each winding, will influence these parameters?
