:PROPERTIES:
:ID:       51f7c5ef-86da-44f3-8d30-b58e676628f3
:END:
#+title: ENG231 - Electrical Machines And Transformers - Assignment 2
#+date: [2024-10-05 Sat 11:01]
#+AUTHOR: Baley Eccles - 652137
#+FILETAGS: :Assignment:TODO:
#+STARTUP: latexpreview
#+LATEX_HEADER: \usepackage[a4paper, margin=2.5cm]{geometry}
#+LATEX_HEADER_EXTRA: \usepackage{minted}
#+LATEX_HEADER_EXTRA: \usepackage{fontspec}
#+LATEX_HEADER_EXTRA: \setmonofont{Iosevka}
#+LATEX_HEADER_EXTRA: \setminted{fontsize=\small, frame=single, breaklines=true}
#+LATEX_HEADER_EXTRA: \usemintedstyle{emacs}
#+LATEX_HEADER_EXTRA: \usepackage[backend=biber,style=apa]{biblatex}
#+LATEX_HEADER_EXTRA: \addbibresource{citation.bib}
#+LATEX_HEADER_EXTRA: \usepackage{float}


* ENG231 - Electrical Machines And Transformers - Assignment 2
** Part 1: Calculation of transformer winding voltages

#+BEGIN_SRC octave :exports both :results output :session Part1
h = 90 *10^(-2);
l = 130 *10^(-2);
d = 22 *10^(-2);
g = 1.8 *10^(-3);
mu0 = 4*pi*10^(-7);
mur = 1800;
A = d^2;
Np = 1360;
Ns = 315;
a=Ns/Np;
f = 50;
I = 3.3;

% Reluctance
%Rgap = g/(mu0*A);
%Rside = (h-2*d-g)/(mu0*mur*A);
%Rbottom = l/(mu0*mur*A);
%Rtop = l/(mu0*mur*A);
%R = 2*Rside + Rbottom + Rtop + 2*Rgap;


Rgap = g/(mu0*A);
RTopGap = (d/2)/(mu0*mur*A);
RTop = (l-d)/(mu0*mur*A);
Rheight = (h-d-g-d/2)/(mu0*mur*A);
RBottom = (l-d)/(mu0*mur*A);
R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;



Phi=(1/R)*Np*I;
V1 = 2*pi*Np*Phi*f/sqrt(2);
V2 = a*V1;

fprintf('Primary Voltage (V1): %.2f V (RMS)\n', V1);
fprintf('Secondary Voltage (V2): %.2f V (RMS)\n', V2);
#+END_SRC

#+RESULTS:
: Primary Voltage (V1): 14849.46 V (RMS)
: Secondary Voltage (V2): 3439.40 V (RMS)

** Part 2: Specification of transformer design to suit application
With the last digit of my student ID being 7:
| Student ID | Rated apparent  | Primary side rated  | Secondary side rated | 3-phase         |
| last digit | power (3-phase) | voltage (line-line) | voltage (line-line)  | connection type |
| 7          | 460 kVA         | 22 kV               | 400 V                | Δ-Y             |




#+BEGIN_SRC octave :exports code :results output :session Part2
clc
clear
close all

% Turns
VpLineToLineRMS = 22*10^3;
VsLineToLineRMS = 400;
VpPhaseRMS = VpLineToLineRMS*sqrt(3);
VsPhaseRMS = VsLineToLineRMS*sqrt(3);

VpPhasePeak = sqrt(2)*VpPhaseRMS;
VsPhasePeak = sqrt(2)*VsPhaseRMS;

a = VsPhaseRMS/(sqrt(3)*VpPhaseRMS)

Np = 1000;
Ns = Np*a;

% Currnet
S = (460*10^3)/3;
IpLineRMS = S/(sqrt(3)*VpPhaseRMS)
IsRMS = IpLineRMS/(a)

% Flux
f = 50;
Phi = (VpPhaseRMS)/(4.44*Np*f) % These may be wrong I am unsure where the sqrt(3) goes.
Phi = (VsPhaseRMS/sqrt(3))/(4.44*Ns*f)

% Relucatance
R = (1/Phi)*Np*IpLineRMS
R = (1/Phi)*Ns*IsRMS


mu0 = 4*pi*10^(-7);
mur = 2150;
mu = mu0*mur;

g = 10^-3;
% Dimensions
%Rgap = g/(mu0*(d^2));
%RTopGap = (d/2)/(mu*(d^2));
%RTop = (l-d)/(mu*(d^2));
%Rheight = (h-d-g-d/2)/(mu*(d^2));
%RBottom = (l-d)/(mu*(d^2));
%R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;
% This gives one equation with three unknowns
% ploting this:

%R = (l-d)/(mu*(d^2)) + 2*(h-d-g-d/2)/(mu*(d^2)) + (l-d)/(mu*(d^2)) + 2*(d/2)/(mu*(d^2)) + 2*g/(mu0*(d^2));

[h, d] = meshgrid(0:0.5:10, 0:0.5:10);

l = d.*mu.*(2.*g ./ (d.*mu0) + 1 ./ mu + 2.*h ./ (d.*mu) - R.*d - 3 ./ mu - 2.*g ./ (d.*mu) - 2 ./ mu) ./ -2;
figure
surf(h, d, l);
xlabel('h');
ylabel('d');
zlabel('l');
grid on;

figure
contour(h, d, l);
xlabel('h');
ylabel('d');
zlabel('l');
grid on;

d = 2000
h = 4
l = d.*mu.*(2.*g ./ (d.*mu0) + 1 ./ mu + 2.*h ./ (d.*mu) - R.*d - 3 ./ mu - 2.*g ./ (d.*mu) - 2 ./ mu) ./ -2
Np
Ns

#+END_SRC

#+RESULTS:
#+begin_example
a = 0.010497
IpLineRMS = 4.0240
IsRMS = 383.33
Phi = 0.099099
Phi = 0.099099
R = 4.0605e+04
R = 4.0605e+04
d = 2000
h = 4
l = 2.1942e+08
Np = 1000
Ns = 10.497
#+end_example




#+BEGIN_SRC octave :exports both :results output :session Verification
h = 4;
l = 2.1942*10^8;
d = 2000;
g = 1*10^(-3);
mu0 = 4*pi*10^(-7);
mur = 2150;
A = d^2;
Np = 1000;
Ns = 10.497;
a=Ns/Np;
f = 50;
Ip = 4.0240;

% Reluctance
%Rgap = g/(mu0*A);
%Rside = (h-2*d-g)/(mu0*mur*A);
%Rbottom = l/(mu0*mur*A);
%Rtop = l/(mu0*mur*A);
%R = 2*Rside + Rbottom + Rtop + 2*Rgap;


Rgap = g/(mu0*A);
RTopGap = (d/2)/(mu0*mur*A);
RTop = (l-d)/(mu0*mur*A);
Rheight = (h-d-g-d/2)/(mu0*mur*A);
RBottom = (l-d)/(mu0*mur*A);
R = RBottom + 2*Rheight + RTop + 2*RTopGap + 2*Rgap;



Phi=(1/R)*Np*Ip;
Vp = 2*pi*Np*Phi*f/sqrt(2);
Vs = a*Vp;

fprintf('Primary Voltage (Vp): %.2f V (RMS)\n', Vp);
fprintf('Secondary Voltage (Vs): %.2f V (RMS)\n', Vs);
#+END_SRC

#+RESULTS:
: Primary Voltage (Vp): 22014.20 V (RMS)
: Secondary Voltage (Vs): 231.08 V (RMS)

** Part 3: Discussion about transformer design trade-offs
 - Describe the influence that your winding design choices (number of turns and layers) have on transformer size and mass? How might you design for minimum total mass, and what trade-off do you see between iron core mass and copper mass?

However this is obviously not good, as the length is over 1km long.
 - Discuss how maximum operating core flux density impacts the required magnetising current and transformer mass?
 - Calculate, by adding to your code, the winding losses for your transformer (calculated power loss at rated operation, as a % of rated throughput power)? You may assume that the AC resistance in normal operation is 20% larger than the calculated DC resistance (owing to skin effect and elevated temperatures). Discuss how transformer design influences this loss?
 - What aspects of the transformer design (size and mass) or operation (magnetising current, losses) are influenced by core gap width for this transformer?
 - For a power transformer, the main components which influence how it impacts the power system are generally the winding resistance and the leakage reactance. Comment on how you think your design choices, in particular the way you have configured each winding, will influence these parameters?
