:PROPERTIES:
:ID:       4e56786f-9fab-41a3-8d79-937a2de93a6b
:END:
#+title: ENG234 - Lab 3
#+date: [2024-10-06 Sun 12:31]
#+AUTHOR: Baley Eccles - 652137
#+STARTUP: latexpreview

* ENG234 - Lab 3

** _Instructions:_
Your group of two is tasked with designing a small signal audio amplifier.

** _Specifications:_
 - The input signal is generated by an electret condenser with an analogue output.
   - [[https://www.digikey.com/Site/Global/Layouts/DownloadPdf.ashx?pdfUrl=A3A5A5DEB6704A6CAE39DDDB7ED3B68A][ELECTRET CONDENSER MICROPHONE BASICS]]
     - Input: 0-20kHz
 - The output signal will be sampled by a micro controller.
 - Amplifier needs to have an adjustable gain with the option of having a fixed gain if needed.
 - Design should consist of 6 BJT transistors or less.
 - All design choices need to be supported with mathematical calculations - show sufficient workings.
 - Simulation outputs are optional, this will be beneficial if you want to explore non-linear behaviour or discontinuities (optional).
 - No mechanical drawing or design required.

** _Deliverable:_
A data sheet detailing your amplifier. The data sheet must include:
 - A pseudonym for your group – a company name along with all group member names and student IDs.
 - Circuit symbol of amplifier with all pins defined.
 - Table(s) containing all reportable specifications.
 - Figure(s) illustrating experimental recordings.
 - Detailed design of amplifier
 - Bill of materials
 - Photos of built circuit (appendix)
 - Mathematical calculations (appendix)

** _Parts list:_
The parts that can be used in this design are provided in the list below (do note that parts are subject to availability):
Transistors: 2N2907 and 2N2222
Diodes: 1N4148
Capacitors: 1nF, 1.2nF, 1.5nF, 1.8nF, 2.2nF, 2.7nF, 3.3nF, 3.9nF, 4.7nF, 5.6nF, 6.8nF, 8.2nF, 10nF, 12nF, 15nF, 18nF, 22nF, 27nF, 33nF, 39nF, 47nF, 56nF, 68nF, 82nF, 100nF, 120nF, 150nF, 180nF, 220nF, 270nF, 330nF, 390nF, 470nF, 560nF, 680nF, 820nF and 1μF.
Resistors: 10Ω, 12Ω, 15Ω, 18Ω, 22Ω, 27Ω, 33Ω, 39Ω, 47Ω, 56Ω, 68Ω, 82 Ω, 100 Ω, 120 Ω,150 Ω, 180 Ω, 220 Ω, 270 Ω, 330 Ω, 390 Ω, 470 Ω, 560 Ω, 680 Ω, 820 Ω, 1 kΩ, 1.2 kΩ, 1.5 kΩ, 1.8 kΩ, 2.2 kΩ, 2.7 kΩ, 3.3 kΩ, 3.9 kΩ, 4.7 kΩ, 5.6 kΩ, 6.8 kΩ, 8.2 kΩ, 10 kΩ, 12 kΩ, 15 kΩ, 18 kΩ, 22 kΩ, 27 kΩ, 33 kΩ, 39 kΩ, 47 kΩ, 56 kΩ, 68 kΩ, 82 kΩ, 100 kΩ, 120 kΩ, 150 kΩ, 180 kΩ, 220  kΩ,270 kΩ, 330 kΩ, 390 kΩ, 470 kΩ, 560 kΩ, 680 kΩ, 820 kΩ, 1 MΩ, 1.2 MΩ, 1.5 MΩ, 1.8 MΩ, 2.2 MΩ, 2.7 MΩ, 3.3 MΩ, 3.9 MΩ, 4.7 MΩ, 5.6 MΩ, 6.8 MΩ, 8.2 MΩ, and 10 MΩ.

** _Important instructions:_
(a) Do not forget to add the correct prefix and SI units.
(b) Note: You will NOT be allowed to enter the laboratory session if you have not completed your initial designs.
(c) Note: You will be allowed to enter the laboratory session if you comply with all safety requirements!
** _Our Design:_
*** Ideas
 - Voltage divider bjt with input and output impedance matching using two extra bjts

*** Calculations
#+BEGIN_SRC octave :exports both :results output :session Calc
clear
clc
close all
pkg load symbolic
syms

%% Values that are going to be used


#+END_SRC
