:PROPERTIES:
:ID:       e1a8a179-0487-4d1f-ad59-83ebeb8cad0c
:END:
#+title: ENG307 - Electrical and Mechatronic Design - Design Assignment 1
#+date: [2025-02-27 Thu 15:30]
#+AUTHOR: Baley Eccles - 652137
#+STARTUP: latexpreview
#+FILETAGS: :UTAS:2025:

* ENG307 - Electrical and Mechatronic Design - Design Assignment 1
 - [[file:~/UTAS/ENG307 - Electrical and Mechatronic Design/Assignment1/Assignment1.odt][Report]]
 - [[file:~/UTAS/ENG307 - Electrical and Mechatronic Design/Assignment1/ENG307-Assignment1-Design-Sheet-Baley-Eccles.xlsm][Assignment Sheet]]

** Exercise 1 - Specifications
*** LED
 - An LED that is visible in day and night lighting conditions
   - It must brighten during the day and dim during the night
 - [[https://coloer.com/blogs/news/guide-to-outdoor-lighting-brightness]]

*** Speakers
 - Speaker(s) must be loud enough to overcome the ambiant outside noise.
 - [[https://soundproof.expert/decibel-chart-noise-level/]]
 - Metric
   - Greater than 50dB
     - Must be able to hear during the rain
*** Microphone
 - The voice must be clear
   - Senistive to 20Hz - 20KHz
     - [[https://en.wikipedia.org/wiki/Microphone#Measurements_and_specifications]]

*** Dimensions
 - The door bell must not be too heavy/large
   - So it can be wall mounted
 - [[https://static.ring.com/assets/static/RING-MEDIA-KIT-8818533c56ed35d9abb217b36c110282.pdf]]
   - 4.98 in. x 2.43 in. x 0.87 in
*** Wi-Fi
 - Wi-Fi must be strong enough to reach on the other side of the house
   - It must be strong enough to go through multiple walls
*** Metrics
 - Force of button https://ergoweb.com/force-guidelines/
 - Mic sens https://www.knowles.com/docs/default-source/default-document-library/mm25-33663-000.pdf?Status=Master&sfvrsn=c3ae71b1_0
 - Speaker Vol https://soundproof.expert/decibel-chart-noise-level/
 - Light brightness https://coloer.com/blogs/news/guide-to-outdoor-lighting-brightness
   - https://www.lightingcouncil.com.au/wp-content/uploads/2018/12/Lighting-Council-Australia-LED-Buyers-Guide.pdf
 - Wi-Fi https://en.wikipedia.org/wiki/IEEE_802.11
   - https://www.whippedcreamsounds.com/mp3-bitrate-differences/
** Exercise 2 - System Topology
*** AC -> DC
 - Mains powered (240V AC)
   - The door bell must reduce the power for the LED and other components
   - AC -> DC converter
     - 5V? 10V? 15V?
*** Microphone
**** Filter
 - The microphone must have a filter on it
   - It will be outside, so there will be background noise
*** Speaker
*** LED
**** Change Brightness
*** Wi-Fi Rx/Tx
** Exercise 3 - Test Cases
*** AC -> DC
 - 
*** Microphone
**** Filter
*** Speaker
*** LED
**** Change Brightness
*** Wi-Fi Rx/Tx

* Page 1
** Exercise 1
_THIS WAS LONGISH_
It was decided from the design description that the door bell would have three main input methods, a button, a microphone and an application that would connect via Wi-Fi. The button is intended to be used to activate the microphone, this ensures that the microphone is not constantly listening to its surroundings, it will also play a chime when pressed. The microphone should be used to capture audio from people at the door, these messages will be stored on the internal storage device, before being sent to the mobile phone application via Wi-Fi. The application is able to play the stored audio recordings.

It was also decided that there would be three output methods, a speaker, an indicator light and various methods in the application. The speaker should be used to play door bell chimes and the aforementioned audio recordings, the speaker must be loud enough for the user to hear, as the door bell will be outside, where there potentially a lot of ambient noise. The indicator light will indicate the status of the door bell by changing colours, the light must be visible under the natural day light. The application is able to connect to external speakers to play door bell chimes when a person has pressed the button, this allows the user to know someone is at the door where ever they are in the house. The application is also able to receive notifications, which will notify the user when someone is at the door or has left a message.

The door bell is powered by 240V AC. This gives the user an easy method for installing the door bell, they will not be required to change batteries or recharge the door bell.

A full specification list can be seen in *TODO* Table A. And their metrics can be seen in *TODO* Table B.

** Exercise 2
A table containing the component hierarchy can be seen in Table C. A hierarchical topology can be seen in Figure E. And system block diagram can be seen in Figure E.
** Exercise 3

** Exercise 4


