:PROPERTIES:
:ID:       091d3056-df3b-466d-8d5a-3d309e5a07f0
:END:
#+title: ENG307 Electrical and Mechatronic Design - Project
#+date: [2025-04-03 Thu 15:37]
#+AUTHOR: Baley Eccles - 652137
#+STARTUP: latexpreview
#+FILETAGS: :Assignment:UTAS:2025:

* Project Report 1

** Components
 - User Input Circuit
   - Buttons
   - Capacitors and resistors
 - Arduino Interface
   - Connects everything together.
 - Power Management
   - voltage regulator
     - L7805
   - PMOS transistor and Zener diode
     - For voltage control.
 - Water Level and Environmental Sensors
   - Pressure sensor
     - instrumentation amplifiers
     - Decide between a INA350AB or a INA350CD
       - Two gain options each
       - INA350ABS: 10 or 20
       - INA350CDS: 30 or 50

   - Temperature Sensor
     - $47k\Omega$ NTC thermistor
 - Motor Control
   - MCP601 Op-Amp
     - input and feedback resistors to set the gain.
   - Motor Driver
     - choose resistors and capacitors
     - Current Sensing Resistor:
       - Default value of $0.1\Omega$
 - Pinch Valve Control
   - servo motor
 - I2C LCD Interface
 - Mounting and Test Points



*** INA350AB vs INA350CD
[[https://www.ti.com/lit/ds/symlink/ina350.pdf?ts=1743655709799&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FINA350]]
Table 6.1: Pin Functions
Gain select – logic low (G = 10 for INA350ABS and G = 30 for INA350CDS)
Gain select – logic high (G = 20 for INA350ABS and G = 50 for INA350CDS)
Gain select – no connect (G = 20 for INA350ABS and G = 50 for INA350CDS)

7.5 Electrical Characteristics (continued)
| Logic low threshold voltage (Gain Select)  | G = 10 for INA350ABS, G = 30 for INA350CDS |
| Logic high threshold voltage (Gain Select) | G = 20 for INA350ABS, G = 50 for INA350CDS |

8.1 Overview
INA350ABS has two gain options of 10 and 20. INA350CDS has two other gain options of 30 and 50

* Project Report 2

** Temperature Sensing
#+BEGIN_SRC octave :exports code :results output :session TEMP
clc;
clear;
close all;

if exist('OCTAVE_VERSION', 'builtin')
  set(0, "DefaultAxesFontSize", 25);
end

% Input Voltage
Vin = 5;

%      5   -> 30 degrees C
%      30k -> 150k
R_therm = 30e3:1:150e3;

% Take the middle value
R = 67e3;

% Calculate the output voltage
Vout = Vin .* (R)./(R + R_therm);
maxV = max(Vout);
minV = min(Vout);
range = (maxV - minV)/Vin;

figure;
plot(R_therm, Vout, 'linewidth', 2)
title("Voltage Divider Voltage Graph");
xlabel("R_{therm}");
ylabel("V_{out}");
print -dpng 'ENG307_Thermistor_Plot.png'

fprintf("The voltage range is from %.2f to %.2f\n", minV, maxV)
fprintf("The percentage of the output voltage is %.3f%%\n", range)
#+END_SRC

#+RESULTS:
: minV = 1.5438
: The voltage range is from 1.54 to 3.45
: The percentage of the output voltage is 0.382%

\[V_{out} = V_{in} \frac{R2}{R1 + R2}\]

\[\Delta V_{out} = V_{out}(R1 = 30 k\Omega) - V_{out}(R1 = 150 k\Omega)\]
\[\Delta V_{out} = V_{in}\frac{R}{30k + R} - V_{in}\frac{R}{150k + R}\]
\[\Delta V_{out} = V_{in}\left[\frac{R}{30k + R} - \frac{R}{150k + R}\right]\]
\[\frac{\Delta V_{out}}{V_{in}} = V_{range} = \frac{R}{30k + R} - \frac{R}{150k + R}\]
We want to find maximum of $V_{range}$. Using some basic calculus, we find $\max(V_{range}) = 38.2%$ and that occurs at $R = 67k\Omega$.

** Button Denouncing
\[\tau = RC\]
If we assume that the button takes less than 5ms to bounce. We can find the resistor and capacitor values:
\[\tau = 10k\cdot 100n\]
\[4\tau = 0.004\ s = 4ms\]
Where $4\tau$ is the amount of time for the charge to reach $98%%$ of the maximum voltage. 


