:PROPERTIES:
:ID:       64e60aa6-00d4-4bc6-8854-1eadf19075a2
:END:
#+title: KIT107 - Programming - Assignment 2
#+date: [2025-04-20 Sun 19:21]
#+AUTHOR: Baley Eccles - 652137
#+STARTUP: latexpreview
#+FILETAGS: :Assignment:UTAS:2025:

* KIT107 - Programming - Assignment 2
[[file:~/UTAS/KIT107 - Programming/KIT107Assignment2/src/AssigTwo125.java]]
[[https://github.com/BaleyEccles/KIT107Assignment2][Github repo]]

** a
sorted list.
Allows us to sort the eggs based on their volume. And will allow us to easily access the data.

** b
Linked List.
The eggs will be stored in order of volume, so using a linked list will allow us to dynamically adjust the data. If an array was used the memory would be constantly changing when adding eggs, which would be slow. Hence, using a linked list will allow us to add eggs without moving a lot memory many times.

** c
Dynamic Array.
Allows us to add any amount of data without having to worry about managing it size. We don't know how many chocolatiers there are in total, we only know that there will be at least, and we will need to find the total of unused eggs.

** d
Array.
The order of the chocolatiers don't matter, so we won't need to move any of the data. We can simply append the next chocolatier to the end of the array.

