:PROPERTIES:
:ID:       25c6c6a6-d98c-439f-81a3-16ddccfa12ec
:END:
#+title: ENG442 - Advanced Digital Electronics - Portfolio
#+date: [2026-02-24 Tue 09:56]
#+AUTHOR: Baley Eccles - 652137
#+STARTUP: latexpreview

* Week 1
** Problem 1
a) Briefly describe the purpose of a look up table (LUT).
b) Briefly describe the purpose of a slice (or equivalently a configurable logic block).
A configurable logic block is the fundamental component of FPGAs, it allow the implementation of logic and memory. The ug474 7Series CLB contains lookup tables, memory, shift registers, multiplexer and few more things.
c) Briefly describe the purpose of the switch matrix.
Allows connections between CLBs, inputs and outputs.
d) With reference to the switch matrix, how might a CLB/Slice output be fed back to its input?
The output of the CLB will be physically connected to a wire, the switch matrix will be used to connect this wire back to the physical input of the CLB.

** Problem 2
Consider the following code and answer the following Verilog questions. This code is for use on the Basys3 development board which has 16 switches (sw) and 16 LEDs (led).
#+BEGIN_SRC verilog
module calc(input [15:0] sw, output [15:0] led);
   assign led = sw;
endmodule
#+END_SRC
a) How many bits are input to the module?
16
b) How many bits are output from the module?
16
c) What does the module do?
enables/disables the 16 LEDs based on the 16 switch inputs
d) Rewrite the module to take only the lower 8 bits from the switches and output to the lower 8 LEDs. Also, change the module so that the switch must be off to turn the corresponding LED on.
#+BEGIN_SRC verilog
module calc(input [7:0] sw, output [7:0] led);
   wire not_sw;
   not not1(not_sw, sw[7:0]);
   assign led = not_sw;
endmodule
#+END_SRC
** Problem 3
Write a Verilog module to implement a full adder.
#+BEGIN_SRC verilog
module adder(input A, input B, input Cin, output sum, output Cout);
   assign sum = A ^ B ^ Cin;
   assign Cout = A && B || Cin && (A ^ B);
endmodule

module test;
   reg a, b, cin;
   wire sum, cout;
   adder dut(a, b, cin, sum, cout);
   initial begin
      a = 0;
      b = 0;
      cin = 0;
      $monitor("%b + %b + %b = %b, %b", a, b, cin, sum, cout);
      for (integer i = 0; i < 8; i = i + 1) begin
         {a, b, cin} = i; // Concatenate i into {a, b, cin}
         #1; // Wait for the outputs to stabilize
      end
   end
endmodule
#+END_SRC

* Week 2
** Problem 1
test text
#+BEGIN_SRC verilog :tangle /home/baley/UTAS/ENG442 - Advanced Digital Electronics/Portfolio/Week_2_Problem_1/Week_2_Problem_1.srcs/constrs_1/new/constrains.xdc :comments link
## Switches
set_property PACKAGE_PIN V17 [get_ports {sw[0]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw[1]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw[2]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw[3]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property PACKAGE_PIN W15 [get_ports {sw[4]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property PACKAGE_PIN V15 [get_ports {sw[5]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property PACKAGE_PIN W14 [get_ports {sw[6]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property PACKAGE_PIN W13 [get_ports {sw[7]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]

set_property PACKAGE_PIN V2 [get_ports {sw[8]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
set_property PACKAGE_PIN T3 [get_ports {sw[9]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
set_property PACKAGE_PIN T2 [get_ports {sw[10]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
set_property PACKAGE_PIN R3 [get_ports {sw[11]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
set_property PACKAGE_PIN W2 [get_ports {sw[12]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
set_property PACKAGE_PIN U1 [get_ports {sw[13]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
set_property PACKAGE_PIN T1 [get_ports {sw[14]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
set_property PACKAGE_PIN R2 [get_ports {sw[15]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]

#+END_SRC

#+BEGIN_SRC verilog :tangle /home/baley/UTAS/ENG442 - Advanced Digital Electronics/Portfolio/Week_2_Problem_1/Week_2_Problem_1.srcs/sources_1/new/Full_Adder.v :comments link
`timescale 1ns / 1ps

module Full_Adder(input A, input B, input Cin, output sum, output Cout);
   assign sum = A ^ B ^ Cin;
   assign Cout = A && B || Cin && (A ^ B);
endmodule
#+END_SRC

#+BEGIN_SRC verilog :tangle /home/baley/UTAS/ENG442 - Advanced Digital Electronics/Portfolio/Week_2_Problem_1/Week_2_Problem_1.srcs/sources_1/new/8bit_adder.v :comments link :tangle no
`include "Full_Adder.v"
`timescale 1ns / 1ps

module Bit_Adder(input [15:0] sw, output [8:0] led);
   wire carry_1;
   Full_Adder(sw[0], sw[8], 0, led[0], carry_1);
   wire carry_2;
   Full_Adder(sw[1], sw[9], carry_1, led[1], carry_2);
   wire carry_3;
   Full_Adder(sw[2], sw[10], carry_2, led[2], carry_3);
   wire carry_4;
   Full_Adder(sw[3], sw[11], carry_3, led[3], carry_4);
   wire carry_5;
   Full_Adder(sw[4], sw[12], carry_4, led[4], carry_5);
   wire carry_6;
   Full_Adder(sw[5], sw[13], carry_5, led[5], carry_6);
   wire carry_7;
   Full_Adder(sw[6], sw[14], carry_6, led[6], carry_7);
   wire carry_8;
   Full_Adder(sw[7], sw[15], carry_7, led[7], carry_8);
   assign led[8] = carry_8;
endmodule
#+END_SRC

** Problem 2

#+BEGIN_SRC verilog :tangle /home/baley/UTAS/ENG442 - Advanced Digital Electronics/Portfolio/Week_2_Problem_1/Week_2_Problem_1.srcs/sources_1/new/8bit_adder.v :comments link
`include "Full_Adder.v"
`timescale 1ns / 1ps

module Bit_Adder(input [15:0] sw, output [8:0] led);
   wire [7:0] carry;

   assign led[0] = sw[0] ^ sw[8];
   assign carry[0] = (sw[0] & sw[8]);

   assign led[1] = sw[1] ^ sw[9] ^ carry[0];
   assign carry[1] = (sw[1] & sw[9]) | (carry[0] & (sw[1] ^ sw[9]));

   assign led[2] = sw[2] ^ sw[10] ^ carry[1];
   assign carry[2] = (sw[2] & sw[10]) | (carry[1] & (sw[2] ^ sw[10]));

   assign led[3] = sw[3] ^ sw[11] ^ carry[2];
   assign carry[3] = (sw[3] & sw[11]) | (carry[2] & (sw[3] ^ sw[11]));

   assign led[4] = sw[4] ^ sw[12] ^ carry[3];
   assign carry[4] = (sw[4] & sw[12]) | (carry[3] & (sw[4] ^ sw[12]));

   assign led[5] = sw[5] ^ sw[13] ^ carry[4];
   assign carry[5] = (sw[5] & sw[13]) | (carry[4] & (sw[5] ^ sw[13]));

   assign led[6] = sw[6] ^ sw[14] ^ carry[5];
   assign carry[6] = (sw[6] & sw[14]) | (carry[5] & (sw[6] ^ sw[14]));

   assign led[7] = sw[7] ^ sw[15] ^ carry[6];
   assign carry[7] = (sw[7] & sw[15]) | (carry[6] & (sw[7] ^ sw[15]));

   assign led[8] = carry[7];
endmodule
#+END_SRC
