:PROPERTIES:
:ID:       be11039b-a9b2-4a47-a5ca-9f6c2b581ce2
:END:
#+title: Model Predictive Control (MPC) With Constraints
#+date: [2026-05-03 Sun 05:10]
#+AUTHOR: Baley Eccles - 652137
#+STARTUP: latexpreview

* Model Predictive Control (MPC) With Constraints
MPC allows the direct and natural incorporation of constraints

** Formulation of Constrained Control Problems
$\Delta u[k]\leftarrow$ modify this when a constraint becomes active
_Notation:_
\[J = \frac{1}{2}x^TEx + x^TF\]
 - $\frac{1}{2}x^TEx$ Quadratic term
 - $x^TF$ Linear term
 - $x$ is not a state vector
 - $Mx \leq \gamma$ constraints 

*** Unconstrained Solution
\[x^{*} = \min_x\{J(x)\},\ x\in \mathbf{R}^n\]
1. $x^{*}$ may not exist if $J(x)$ has no lower bound
   - Assume that $J(k)$ is _bounded below_
2. While the global minimum is most optimal, we struggle to find it efficiently. Finding a local minimum is considered sufficient.
   
Fist and second derivatives of $J(x)$:
\begin{align*}
g(x) &= \nabla J(x) \\
G(x) &= \nabla^2 J(x)
\end{align*}

Minimised (locally) if:
\[g^{*}(x) &= 0\]
$G(x)$ is positive definite
 - (\[s^TG(x^{*})s > 0\])

Two cases
1. Equality constraints
   - $x = 10$
2. Inequality constraints
   - $-10 < x < 3$

*** Relation to Established MPC Formulation
\[J = (R_s - Y)^TQ(R_s - Y) + \Delta U^T R \Delta U\]
Where:
\begin{align*}
Y &= Fx[k_i] + \Phi \Delta U \\
\Rightarrow J &= \Delta U^T(\Phi Q \Phi + R ) \Delta U - 2 \Delta U^T \Phi^T Q(R_s - Fx[k_i])
\end{align*}

General quadratic optimisation:
\[J = \frac{1}{2}x_0^TE_0x_0 + x_0^TF\]

_Conclude that:_
 - \[\Delta U = x_0\]
   - The quantity to optimise
 - \[E_0 = 2\left(\Phi^TQ\Phi + R\right)\]
 - \[F_0 = 2\Phi^TQFx[k] - 2\Phi^TQR_s\]

*** Example
Establish $E_0$ and $F_0$ for the state space dynamics given by:
\[\dot{x}_m &= A x_m + B u\]
\[y = Cx_m\]
Given $N_p$, $N_c$, $T_s$, $r$, $R$ and implied $Q = I$
Initial state $x_m(0) = [\hdots]$
Find the unconstrained optimiser $\Delta U[0]$

**** Solution
1. Convert continuous matrices to discrete matrices
\[A_m = A(T_s) = I + AT_s + \hdots + \frac{A^kT_s^k}{k!}\]
 - Choose a $k$ (about 5 is good)
\[B_m = B(T_s) = T_sI + \frac{T_s^2 A}{2!} + \hdots\]
 - Choose a $k$ (about 5 is good)
\[C_m = C(T_s) = C\]
 - Does not change, same with $D$
   
2. Augmented system for MPC
Plug matrices into:
\begin{cases}
\begin{bmatrix}
\Delta x_m[k+1] \\
y[k+1]
\end{bmatrix} &= \begin{bmatrix}
A_m & 0 \\
C_mA_m & 1
\end{bmatrix}\begin{bmatrix}
\Delta x_m[k] \\
y[k]
\end{bmatrix} + \begin{bmatrix}
B_m \\
C_mB_m
\end{bmatrix}\Delta u[k] \\
y[k] &= [0\ 1]\begin{bmatrix}
\Delta x_m[k] \\
y[k]
\end{bmatrix}
\end{cases}
 - This gives new $A$, $B$ and $C$ matrices
   
3. Find $F$, $\Phi$ and $R_s$
Plug into:
\[F &= \begin{bmatrix}
CA \\
CA^2 \\
\vdots \\
CA^{N_p}
\end{bmatrix}\]
And:
\[\Phi &= \begin{bmatrix}
CB & 0 & 0 & 0 & 0 \\
CAB & CB & 0 & 0 & 0 \\
CA^2B & CAB & CB & 0 & 0 \\
\vdots & \vdots & \vdots & \vdots & \vdots \\
CA^{N_p-1}B & CA^{N_p-2}B & CA^{N_p-3}B & \hdots & CA^{N_p-N_c}B
\end{bmatrix}\]
And:
\[R_s = \begin{bmatrix}
1 \\
1 \\
\vdots \\
1
\end{bmatrix} r[k_i]\]

4. Use initial state
\[x_m[0] = A_mx_m[-1] + B_mu[-1]\]
Assume $u[-1] = 0$
 - We have no control before $k = 0$
   
Use $x_m(0)$ to find $x_m[-1]$
\begin{align*}
x_m(0) &= A_mx_m[-1] + B_m0 \\
x_m[-1] &= A_m^{-1}x_m(0)
\end{align*}

5. So,
\[\Delta x_m[0] = x_m[0] - x_m[-1]\]

Also need $y[0]$:
\[y[0] = C_mx[0]\]

6. Plug into augmented matrix
\[x[0] = [\hdots]\]

7. unconstrained MPC (Find $E_0$ and $F_0$)
\[E_0 = 2\left(\Phi^TQ\Phi + R\right)\]
\[F_0 = 2\Phi^TQFx[k] - 2\Phi^TQR_s\]
 - Use $x[0]$ for $x[k]$ and find other one later

8. The unconstrained optimiser
\[\Delta U[0] = -E_0^{-1}F_0\]

9. Repeat for each state required

*** Equality Constraints
For vectors in $\mathbf{R}^n$, we introduce a stet that is feasible, and still attempt to minimise $J(x_0)$.

**** Simple Mathematical Example
Minimise $J = (x_1 - 2)^2 + (x_2 - 2)^2$
Subject to $x_1 + x_2 = 1$
 - The unconstrained solution is $(x_1, x_2) = (2, 2)$
   - This does not meet the constraint ($2 + 2 \neq 1$)
Substitute constraint:
\begin{align*}
J &= (x_1 - 2)^2 + (1 - x_1 - 2)^2 \\
J &= 2x_1^2 - 2x_1 + 5 \\
\frac{dJ}{dx_1} &= 0 \\
\Rightarrow 0 &= 4x_1 - 2 \\
\Rightarrow x_1 &= 0.5 \\
\Rightarrow x_2 &= 0.5
\end{align*}

Lagrange Multipliers solve the general constrained optimisation problem.
Augment $J(x_0)$ with a vector of Lagrange Multipliers $\lambda$, giving:
\[J(x_0,\lambda) = \frac{1}{2}x_0^TF_0x_0 + x_0^TF_0 + \lambda^T(Mx_0 - \gamma)\]

Minimise:
\begin{align*}
\frac{\partial J}{\partial x} &= 0 \\
\frac{\partial J}{\partial \lambda} &= 0 \\
\Rightarrow & \begin{cases}
E_0 x_0^{*} + F_0 + M^T\Lambda^{*} &= 0 \\
Mx_0^{ *} - \gamma &= 0
\end{cases} \\
\Rightarrow \begin{bmatrix}
x_0^{*} \\
\lambda^{*}
\end{bmatrix} &= \begin{bmatrix}
E_0 & M^T \\
M & 0
\end{bmatrix}^{-1}
\begin{bmatrix}
-F_0 \\
\gamma
\end{bmatrix} \\
\lambda^{*} &= -(ME_0^{-1}M^T)^{-1}(\gamma + ME_0^{-1}F_0) \\
x_0^{*} &= -E_0^{-1}F_0 - E_0^{-1}M^T\lambda^{*}
\end{align*}

$x_0^{*}$ is the unconstrained optimiser and the correction due to constraint

**** Example
\[J = \frac{1}{2}x_0^TE_0x_0 + x_0^TF_0\]
 - Given or found $E_0$ and $F_0$
a) Find unconstrained solution
b) Find constrained solution with
  1. \[x_1 + x_2 + x_3 = 1\]
  2. \[3x_1 - 2x_2 - 3x_3 = 1\]

***** Solution a)
\[x_0^{*} = -E_0^{-1}F_0 = [2\ 3\ 1]^T\]

This gives:
\begin{align*}
J &= \frac{1}{2}x_0^{*^T}E_0x_0^{*} + x_0^{*^T}F_0\\
J &= -7
\end{align*}

***** Solution b)
\[Mx = \gamma\]
 - This is how we write constraints
   
Constraints in matrix form:
\[\begin{bmatrix}
1 & 1 & 1 \\
3 & -2 & -3
\end{bmatrix}\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix} = \begin{bmatrix}
1 \\
1
\end{bmatrix}\]

Plug matrices into:
\[\lambda^{*} &= -(ME_0^{-1}M^T)^{-1}(\gamma + ME_0^{-1}F_0) = [\hdots]\]

Then plug into:
\[x_0^{*} = -E_0^{-1}F_0 - E_0^{-1}M^T\lambda^{*} = [\hdots]\]

Find objective function:
\[J = \frac{1}{2}x_0^{*^T}E_0x_0^{*} + x_0^{*^T}F_0 = -1.6130\]

*** Inequality Constraints
\[Mx_0 \leq \gamma\]
 - Must fit this definition, can multiply by -1 to swap the inequality direction

Two states:
1. Active
   - Meaning we have equality
   - We are at the boundary of an inequality
2. Inactive
   - Meaning we have strict inequality
   - We are between the boundaries of the inequality

Karush-Kuhn-Tucker Conditions:
\begin{align*}
E_0x_0 + F_0 + M^T\lambda &= 0\\
Mx_0 - \lambda &\leq 0 \\
\lambda^T(Mx_0 - \gamma) &= 0 \\
\lambda &\geq 0
\end{align*}

The set of active constraints is $S_{act}$, and each state is denoted by $i$:
\begin{align*}
E_0 x_0 + F_0 + \sum_{i\in S_{act}}\lambda_i M_i^T &= 0 \\
M_ix_0 - \gamma_i &= 0,\ i\in S_{act} \\
\lambda_i &> 0,\ i\in S_{act}
\end{align*}
 - If a constraint is active it has $\lambda_i &> 0$
The inactive constraints meet the conditions:
\begin{align*}
M_ix_0 - \lambda_i &< 0,\ i\notin S_{act} \\
\lambda_i &= 0,\ i\notin S_{act}
\end{align*}
 - If a constraint is inactive it has $\lambda_i &= 0$

**** Example
Optimise $E_0 =[\hdots]$, $F_0 = [\hdots]$, subject to:
\begin{align*}
x_1 + x_2 + x_3 &\leq 1 \\
3x_1 - 2x_2 - 3x_3 &\leq 1 \\
x_1 - 3x_2 + 2x_3 &\leq 1
\end{align*}

***** Solution
Assume all constraints are active:
\begin{align*}
x_1 + x_2 + x_3 &= 1 \\
3x_1 - 2x_2 - 3x_3 &= 1 \\
x_1 - 3x_2 + 2x_3 &= 1
\end{align*}
 - This is $M$ and $\gamma$
Check feasibility:
This set is feasible (there is exactly one solution)

Find Lagrange Multipliers:
\begin{align*}
\lambda^{*} &= -(ME_0^{-1}M^T)^{-1}(\gamma + ME_0^{-1}F_0) \\
\lambda &= [1.6\ 0.0509\ -0.4352]^T
\end{align*}
Positive values suggests the responding equation should move up
Negative values suggests the responding equation should move down

From $-0.4352$, the third constraint is not active, so drop it from the set of active constraints and repeat.
\begin{align*}
x_1 + x_2 + x_3 &= 1 \\
3x_1 - 2x_2 - 3x_3 &= 1
\end{align*}
 - This is $M$ and $\gamma$
   
Reevaluate $\lambda$:
\begin{align*}
\lambda^{*} &= -(ME_0^{-1}M^T)^{-1}(\gamma + ME_0^{-1}F_0) \\
\lambda &= [1.64\ -0.0323]
\end{align*}
From $-0.0323$, the second constraint is not active, so drop it from the set of active constraints and repeat.
\begin{align*}
x_1 + x_2 + x_3 &= 1 \\
\end{align*}
 - This is $M$ and $\gamma$
   
Reevaluate $\lambda$:
\begin{align*}
\lambda^{*} &= -(ME_0^{-1}M^T)^{-1}(\gamma + ME_0^{-1}F_0) \\
\lambda &= [\frac{5}{3}]
\end{align*}
 - $\frac{5}{3}$ implies the first constraint is active
   
Use equality constrains to find the solution
\[x_0^{*} = -E_0^{-1}F_0 - E_0^{-1}M^T\lambda^{*} = [1/3\ 4/3\ -2/3]^T\]

_Let's check:_
\[Mx_0^{*} = [\hdots][\hdots] = [1\ 1/3\ -5]^T \leq [1\ 1\ 1]^T\]

